---
title: "Russia Country Report"
description: Return to [CoronaNet](https://coronanet-project.org/)
author:
  - name: Nazerke Mukhlissova
    url: https://www.linkedin.com/in/nazerke-mukhlissova/
    affiliation: Nazarbayev University
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>


The Russian Federation is an interesting case study to look at when considering health emergency. One reason is because of the country’s decentralized political system, where there are many actors that policies have come from during COVID-19. These include Federal bodies such as Rospotrebnadzor, as well as Moscow, regional bodies and newly organized COVID-19 task forces. Even though each body has its own approach, there is an intersection in these policies.

Starting in March, regions of the Russian Federation started introducing the universal regime of self-isolation.^[Russkiy Mir Foundation. March 31st, 2020. https://russkiymir.ru/en/news/270960/] As President Vladimir Putin put it, citizens were incentivized to self-isolate by “taking [a] couple [of] days off from work”.^[Shok, Nataliya and Beliakova, Nadezhda. June 17th, 2020. Kennedy Institute of Ethics. https://kiej.georgetown.edu/soviet-legacies-pandemic-special-issue/] Following the example of the Federal government, the regional governments used a similar approach. Russians were not allowed to leave their place of residence for any reason, except for necessities like going to the pharmacy and food shopping.  The administration of the Vladimir region used phrases to describe the regime as involving “high preparedness” and “high alert”, rather than using the “emergency state” language that already existed in Russian law. The difference between the introduced regime in contrast to an emergency state is that the Federal and regional governments were not obliged to respond to the fact that many people had lost their jobs, and that many small and medium-sized businesses closed down with no ability to recover in future.^[Shevtsova, Lilia. April 8th, 2020. Berlin Policy Journal. https://berlinpolicyjournal.com/russias-coronavirus-drama/]

When it comes to the formulation of policies, analysis of the Vladimir region and the Chechen Republic shows that there was an interesting trend which led to specific perceptions in society. The policies that demanded the most attention were worded as “recommendations” in terms of type of enforcement. For example, working from home was advised to employers, which technically meant that employers still had the ability to force their workers to come to work, endangering their health.^[Rossiyskaya Gazeta. April 2nd, 2020. https://rg.ru/2020/04/02/vladimir-ukaz63-reg-dok.html] Furthermore, schools in the Vladimir region were never forced to close, but were advised to introduce free attendance, with parents deciding whether to send their kids to school or not.^[The Official Internet Portal of the Administration of the Vladimir region. March 18th, 2020. https://avo.ru/-/vo-vladimirskoj-oblasti-usileny-mery-profilaktiki-koronavirusa] ^[Department of Education of the Vladimir region. March 23rd, 2020. https://xn--80aakec5bilkue.xn--33-6kcadhwnl3cfdx.xn--p1ai/pres-tsentr/news/27695/?sphrase_id=49238] This shows that both Federal and regional governments decided not to take too much responsibility. Rather, they left it to individuals which opened a lot of space for non-compliance. In these cases, where individuals decide not to obey self-isolation, the epidemiological situation got substantially worse. The reasons for taking such a soft stance on such serious issues might have been due to potential pushback from citizens, and the inability of the state to provide for other alternatives such as online education and payment to businesses for shutdowns. Therefore, while the state tried to minimize negative reactions, it seemed to happen at the expense of the collective safety. 

Another interesting factor worth looking at is the frequency at which policies were produced. In many cases, official documents contained a line stating that “the decree/policy comes into force with its date of official publication”. This meant that the day when the decree was published was the same day when it acquired enforcement power. For example, the introduction of “digital badges” in the Vladimir region, which limited internal movement, was announced and enforced the same day. However, this method did not give time for citizens to adapt to the new restrictions and laws.^[The Official Internet Portal of the Administration of the Vladimir region. April 24th, 2020. https://avo.ru/-/utverzden-poradok-oformlenia-i-ispol-zovania-cifrovyh-propuskov-dla-peredvizenia-po-vladimirskoj-oblasti-v-period-dejstvia-rezima-povysennoj-gotovnost] Another example was the lockdown of whole districts without prior notice in a timespan of one day, which likely caused illegal border crossings and non-compliance. When such events occurred quickly, the presence of communication bridges between the government and the citizens was the key step. But while there were public awareness measures conducted by the state, practice showed that it was not done enough. The logic of immediate policy enforcement was that this might be an effective way of stopping the imminent spread of COVID-19. But, in fact it meant that people were violating law without even knowing it, and it caused an extreme increase in the imposition of fines.^[Interfax Russia. May 22nd, 2020. https://www.interfax-russia.ru/koronavirus-v-rossii/narushiteli-samoizolyacii-vo-vladimirskoy-oblasti-oshtrafovany-na-1-5-mln-rubley] Considering that the state (neither Federal nor regional) did not pay much attention to those in difficult positions due to the pandemic, citizens perceived this particularly negatively which amplified annoyance with the state. 

Thirdly, while some restrictions were supposed to ensure safety, they turned out to achieve greater harm for reasons such as poor research and devaluation of the importance of areas prohibited by the government. The head of the Vladimir region, Vladimir Sipyagin, signed a decree which prohibited services such as the operation of drug stores and pet shops as well as delivery of products and food.^[Official Internet Portal of Legal Information. May 12th, 2020. http://publication.pravo.gov.ru/Document/View/3300202005120001?index=0&rangeSize=1] The citizens of the Vladimir region perceived these restrictions as unnecessary because of the substantial complications in finding basic necessities, like medicine. Despite the governor changing his mind quickly and repealing these policies the day after its enforcement, the negative impact on the state-society relationship remained. Ordinary citizens and journalists started questioning the trustworthiness of the administration of the Vladimir region. When distrust was compounded by government actions, there were less incentives to comply with rules in general. Moreover, the consistency of the policies also played a role in the effective battle against COVID-19. With the absence of this trait, the spread of misinformation or confusion took place more frequently. Citizens tended to believe conspiracy theories, rather than official sources.

In conclusion, while activities in the Moscow and Saint-Petersburg regions have been highly scrutinized by the international community, other regions demonstrate the reality of Federal governance in Russia during the COVID-19 crisis. Leaving space for governance by the regional bodies was done with the intention of individual adaption of appropriate policies under different epidemiological situations. Realistically, that turned out to achieve the shift of responsibility on regional government, which in their turn, were not prepared to act on their own. The recommendations of President Putin were certainly heard among the regional governors, but the point is that it was not enough. Flexibility is important, but only once there is more information and guidance on what should be done. While other states around the world were concerned about the cohesiveness of policies coming from different political organs, this was not an issue in Russia. The Federal government was slow and inactive in responding to the crisis. The cases of the Vladimir and Chechen regions are typical for the Russian territory. They serve as a representation of the way that public relations are built, and reveal institutional issues within these regions. 
