---
title: "Israel Country Report"
description: Return to [CoronaNet](https://coronanet-project.org/)
author:
  - name: Aaron Forman
    url: https://www.linkedin.com/in/aaronlforman/
    affiliation: Carleton College
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>

Israel is a Middle Eastern country located on the eastern shore of the Mediterranean Sea, extending from the Golan Heights in the north to the Red Sea beach town of Eilat in the south. In addition to its territory within the “Green Line,” Israel also exercises varying degrees of civil and military authority over parts of the disputed West Bank known as Areas B and C. Israel’s population is approximately 9 million people, and its capital is Jerusalem. The government operates democratically as a parliamentary system, with a unicameral legislature known as the Knesset, a Prime Minister, various ministries, and a President with extremely limited power. Israel is the only country with a majority Jewish population and defines itself as a Jewish state, functioning as a homeland for all Jewish people. Israel declared a state of emergency for the COVID-19 pandemic on March 18, 2020. 

On April 8, the Israel Ministry of Health purchased equipment and supplies to allow for 10,000 additional COVID-19 tests. Israel announced on April 18 that there would be a 200 shekel fine for not wearing a mask, and on June 22 increased the fine to 500 shekels.^[Haaretz. April 19th, 2020. https://www.haaretz.com/israel-news/.premium-netanyahu-announced-easing-coronavirus-restrictions-here-s-what-you-need-to-know-1.8780064] On June 16, Israel signed an agreement with Moderna Inc., a biotechnology company, to purchase its COVID-19 vaccine in the event the company’s tests would succeed.^[The Jerusalem Post. June 16th, 2020. https://www.jpost.com/breaking-news/israel-in-talks-to-buy-coronavirus-vaccine-from-moderna-report-631476] While government efforts to enforce policies and raise public awareness faced more resistance in ultra-Orthodox Jewish cities and neighborhoods like Bnei Brak and Mea Shearim, the country still responded relatively well to its initial wave. By mid-May, Israel stood out as a major success story in quickly adopting measures to close businesses and moving to remote work, as well as enforcing social distancing and mask wearing in public spaces. On May 21, daily new cases reached a low of 16.^[Johns Hopkins University Coronavirus Resource Center. 2020. https://coronavirus.jhu.edu/map.html] 

Policies for the reopening of beaches, gyms, restaurants, and other businesses were intended to revive the hard-hit Israeli economy. However, these reopenings caused the country to experience a far more devastating second wave of the pandemic, with new daily cases reaching a peak of 2,308 on June 28.^[Johns Hopkins University Coronavirus Resource Center. 2020. https://coronavirus.jhu.edu/map.html] Cases of COVID-19 spread particularly quickly in schools that reopened with restrictions on May 3, where some regulations were not well-enforced.^[Sokol, Sam. May 13th, 2020. Jewish Telegraphic Agency. https://www.jta.org/2020/05/13/israel/the-entire-system-got-confused-israeli-schools-reopen-but-many-parents-arent-sending-their-kids-back] As cases increased throughout the country, by June 3, the government ordered all schools that suffered a COVID-19 outbreak to shut down.^[Kershner, Isabel and Belluck, Pam. August 4th, 2020. New York Times. https://www.nytimes.com/2020/08/04/world/middleeast/coronavirus-israel-schools-reopen.html] On September 1, Israel reopened schools for the new school year.^[The Times of Israel. August 24th, 2020. https://www.timesofisrael.com/schools-to-open-september-1-but-only-4th-grade-and-below-to-return-full-time/] A humorous public information video, featuring Prime Minister Benjamin Netanyahu himself, reminded students to study hard, wear masks, and social distance to protect each other and their families.^[Netanyahu, Benjamin. August 31st, 2020. Instagram. https://www.instagram.com/tv/CEj9A5EJZm5/?hl=en] 

The COVID-19 pandemic took hold in Israel during a complex political period since the two elections in April and September 2019 respectively failed to produce a coalition government in the Knesset. The election on March 2 was held under pandemic conditions, with separate polling places for voters in quarantine to prevent potential COVID-19 exposure.^[Oster, Marcy. March 2nd, 2020. Jewish Telegraphic Agency. https://www.jta.org/2020/03/02/israel/israelis-in-quarantine-due-to-coronavirus-exposure-exercise-their-right-to-vote-at-special-polling-locations] While a similar political stalemate followed the March election, Prime Minister Benjamin Netanyahu and his leading opponent, Benny Gantz, agreed to form a coalition to avoid sending the country into a fourth election in the midst of the pandemic. In addition to direct responses taken to prevent the spread of COVID-19 among Israeli citizens, the pandemic has also affected Israel’s policies regarding the Palestinian Territories and the establishment of bilateral relations with the United Arab Emirates (UAE). 

Israel’s COVID-19 response took a controversial turn when the Knesset authorized Israel’s security agency, the Shin Bet, to repurpose counterterrorism techniques for the purpose of monitoring people who had tested positive for the virus. Beginning on March 17, the Shin Bet tracked the movement of virus-positive citizens using cell phone tracking technology to enforce quarantine and lockdown policies. International and domestic privacy rights groups strongly criticized the measure.^[Reuters. July 20th, 2020. https://www.reuters.com/article/us-health-coronavirus-israel-surveillanc/israel-approves-cellphone-tracking-of-covid-19-carriers-for-rest-of-year-idUSKCN24L2PJ] As restrictions eased in May and June, this program ended on June 8. When the second wave of cases arrived, the Knesset voted to reinstate the policy on June 24, requiring the legislature to renew its approval of the policy every 21 days through January 1, 2021. 

Also from March 17, the Israeli Defense Forces (IDF) operated “COVID-19 Hotels". Different hotels were allocated to serve people entering the country, asymptomatic individuals who tested positive, and patients with COVID-19 symptoms respectively.^[Linder, Ronny. April 1st, 2020. Haaretz. https://www.haaretz.com/israel-news/.premium-a-thermometer-for-every-guest-no-room-service-welcome-to-hotel-coronavirus-1.8728357] On May 11, the IDF permitted people with the means to quarantine at home away from family members to do so.^[The Times of Israel. May 11th, 2020. https://www.timesofisrael.com/israel-eases-isolation-hotel-requirements-for-incoming-travelers-opens-parks/] Nearing the end of the initial end date of the program, August 31, the IDF cut seven of the 28 hotels from the program.^[Ahronheim, Anna. August 25th, 2020. The Jerusalem Post. https://www.jpost.com/israel-news/seven-coronavirus-hotels-to-close-by-end-of-the-week-639857]  

Israel took major steps in adjusting its bureaucracy in order to deal with COVID-19 more efficiently. On March 24, the Knesset established a Coronavirus Committee to oversee the country’s response.^[Wootliff, Raoul. March 24th, 2020. The Times of Israel. https://www.timesofisrael.com/knesset-votes-to-form-coronavirus-committee-other-oversight-bodies/] On July 7, the Knesset authorized the Coronavirus Committee to make decisions that would go into effect before being debated and voted on by the Knesset as a whole. The Knesset was still required to approve the measure within seven days, with a possible three day extension, after which the measure would be cancelled if not approved.^[Lis, Jonathan, Landau, Noa and Peleg, Bar. July 7th, 2020. Haaretz. https://www.haaretz.com/israel-news/.premium-israeli-government-pushes-bill-to-bypass-knesset-on-coronavirus-regulations-1.8974245] On July 21, the government created a new position to lead the country’s COVID-19 response, which was nicknamed the “Coronavirus Czar.” Ronni Gamzu, the CEO of the Sourasky Medical Center in Tel Aviv, accepted the position on July 22 and, as of September, continues to lead the country’s response effort. On July 28, Gamzu implemented the “Shield of Israel” strategic plan. The plan implored citizens to cooperate with the government’s regulations, placed the IDF in charge of testing and contact tracing, consolidated the Ministry of Health’s data and statistics on the virus, and increased testing to 60,000 per day within the month of August and 100,000 per day by the winter.^[Jaffe-Hoffman, Maayan. July 28th, 2020. The Jerusalem Post. https://www.jpost.com/health-science/coronavirus-czar-debuts-defend-israel-strategic-plan-636656] 

As the only country with a majority Jewish population and also home to several devout religious communities, Israel enacted policies that reflect its demographic makeup. The Ministry of Health initiated public awareness campaigns in April to prevent the spread of COVID-19 during Passover and Ramadan celebrations.^[Israeli Ministry of Health. April 19th, 2020. https://www.gov.il/en/departments/news/18042020_01] ^[Israeli Ministry of Health. April 7th, 2020. https://www.gov.il/en/departments/news/07042020_5] On April 17, Israel announced a health resources initiative to create high-density cotton masks specifically designed to fit men with large beards. This is because many Haredi Jews, religious Muslims, and Orthodox Christian priests in Israel grow beards for religious reasons.^[The Times of Israel. April 19th, 2020. https://www.timesofisrael.com/israel-mass-produces-washable-masks-that-fit-kids-adults-and-beards/] On July 29, Israel’s Chief Ashkenazi Rabbi, David Lau, issued a ruling that Jews with COVID-19, including asymptomatic cases, should not fast for the Tisha b’Av holiday. He also insisted that Jews use hand sanitizer and wash their hands on the holiday, which is normally prohibited.^[Oster, Marcy. July 29th, 2020. The Times of Israel. https://www.timesofisrael.com/israels-chief-rabbi-coronavirus-patients-should-not-fast-on-tisha-bav/]  

While Israel has been a focus of geopolitical news beyond COVID-19 over the past few months, the pandemic influenced Israel’s annexation plans for parts of the West Bank on July 1 and an agreement reached with the UAE on August 13. When July 1 arrived, Deputy Prime Minister Benny Gantz “expressed a desire for Israel to deal with the economic ravages of the coronavirus crisis” before addressing the annexation issue.^[Beaumont, Peter and Scammel, Rosie. June 29th, 2020. The Guardian. https://www.theguardian.com/world/2020/jun/29/netanyahus-annexation-plan-in-disarray-as-gantz-calls-for-delay] On June 25, Netanyahu announced a partnership with the UAE to fight COVID-19, which the UAE stated was an agreement for technological development between four private Israeli and Emirati companies with government assistance. The UAE also used the opportunity to state that Israel continuing with its annexation plans would negate the progress that the two countries had made toward normalization.^[Bergman, Ronen and Hubbard, Ben. June 25th, 2020. New York Times. https://www.nytimes.com/2020/06/25/world/middleeast/israel-united-arab-emirates-coronavirus.html?fbclid=IwAR1TSeDY-esYxnc0KNPg1IiYjcLbSFvg2SCyEBCIrxVtdHV55ttWnE_OhxM&login=email&auth=login-email] Indeed, Israel did not annex territory in the West Bank on July 1. On August 13, Israel and the UAE announced the establishment of formal relations in an official statement. The statement itself includes the following: “The United Arab Emirates and Israel will immediately expand and accelerate cooperation regarding the treatment of and the development of a vaccine for the coronavirus. Working together, these efforts will help save Muslim, Jewish, and Christian lives throughout the region.”^[The White House. August 13th, 2020. https://www.whitehouse.gov/briefings-statements/joint-statement-united-states-state-israel-united-arab-emirates/] It is clear that the effort to work together against the spread of COVID-19 played an important role in the establishment of relations between the two nations.

On July 25, thousands of citizens in Jerusalem, Tel Aviv, Caesarea, Ramat Gan, and other cities protested the government’s failure to prevent economic hardship and suffering throughout the country. Some business owners defied government orders to close, citing the weekend restriction that took effect on July 17 as an effort by religious parties to reduce trade activity on Shabbat rather than actually prevent the spread of COVID-19.^[The Times of Israel. July 17th, 2020. https://www.timesofisrael.com/numerous-restaurants-to-stay-open-over-weekend-bucking-new-lockdown-measures/] The Knesset rolled back weekend business restrictions on August 7.^[Jaffe-Hoffman, Maayan. August 6th, 2020. The Jerusalem Post. https://www.jpost.com/breaking-news/coronavirus-in-israel-24866-active-cases-over-100-intubated-637559] School reopening policies and Coronavirus Czar Ronni Gamzu’s “Traffic Light” plan to provide municipal governments with greater authority in decision making are in effect as of September 1.^[Jaffe-Hoffman, Maayan. August 6th, 2020. The Jerusalem Post. https://www.jpost.com/health-science/coronavirus-in-israel-what-is-the-policy-for-red-and-orange-cities-637635] With 111,493 active cases and 891 deaths so far, Israel finds itself at a critical juncture in its pandemic response, and the effectiveness of these new policies will be monitored closely.^[Johns Hopkins University Coronavirus Resource Center. 2020. https://coronavirus.jhu.edu/map.html] 

