---
title: "The Gambia Country Report"
description: Return to [CoronaNet](https://coronanet-project.org/)
author:
  - name: Will Yoh
    url: https://www.linkedin.com/in/will-yoh-45a7ab162/
    affiliation: Duke University
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>

While COVID-19 continues to spread across the globe, The Gambia has managed to slow the spread, having only 64 positive cases resulting in 3 deaths.^[WorldOMeter July 14th, 2020 https://www.worldometers.info/coronavirus/country/gambia/] The small population has aided the country in keeping infection rates down. Even with country size accounted for, The Gambia is faring better than most countries in limiting the impact of the virus.^[WorldOMeter July 15th, 2020https://www.worldometers.info/world-population/gambia-population/] For instance, The Gambia was in the top 15 (of countries ranked) in terms of lowest deaths per million at 0.88 deaths per million people, with only two deaths at the time.^[de Best, Raynor Statista July 1st, 2020https://www.statista.com/statistics/1104709/coronavirus-deaths-worldwide-per-million-inhabitants/] While countries seek to avoid death related to the virus, the current case count in The Gambia compared with the rest of the world seems promising. For instance, Senegal, which surrounds The Gambia, has 7.06 deaths per million people, significantly higher than The Gambia.^[de Best, Raynor Statista July 1st, 2020 https://www.statista.com/statistics/1104709/coronavirus-deaths-worldwide-per-million-inhabitants/] Furthermore, many countries have had hundreds of deaths per million. Such as the United States, which has had 388 deaths per million people.^[de Best, Raynor Statista July 1st, 2020 https://www.statista.com/statistics/1104709/coronavirus-deaths-worldwide-per-million-inhabitants/] If the U.S. had the same death rate as The Gambia, only 290 individuals would have died, while over 130,000 have.^[CDC July 14th, 2020 https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/us-cases-deaths.html]

The Gambia has suppressed the spread of the virus by implementing strong measures early. On March 17th, following the first reported case of COVID-19 in The Gambia, external border restrictions were already implemented with preventive measures at airports, and public officials blocked from traveling overseas.^[APA News March 2nd, 2020 http://apanews.net/en/pays/gambie/news/angst-in-gambia-as-coronavirus-confirmed-in-senegal] Unlike some more developed countries, The Gambia did not wait for the virus to reach them. Instead, it began taking measures weeks before the first case arrived and continued to be stern ever since. 

While The Gambia has avoided a large scale outbreak thus far, the country may not be able to handle it if there were to be one. The Gambia has only 1.13 hospital beds per 1,000 people and 11 physicians per 100,000 people.^[International Travel & Health Insurance Journal July 31st, 2012 https://www.itij.com/latest/long-read/healthcare-and-assistance-gambia] The economy does not produce enough money to match what is required by the public health system, and the system could be “close to a breaking point,” as cited by a pre-pandemic report.^[International Travel & Health Insurance Journal July 31st, 2012   https://www.itij.com/latest/long-read/healthcare-and-assistance-gambia] The national government, specifically President Adama Barrow, likely keeps this in mind as he continues to implement strict COVID-19 policies. Additionally, a state of public emergency has been in effect since March 27th, with Barrow extending it on four occasions, most recently on July 7th until July 15th.^[Twitter. (@Presidnecy_GMB) July 7th,2020 https://twitter.com/Presidency_GMB/status/1280553776672313346]

While the policy response has been effective and stronghanded, the government has begun to feel pressure to allow people to return to normal. On June 4th, markets were allowed to open for certain hours following health protocols.^[Twitter. (@Presidency_GMB) June 5th, 2020 https://twitter.com/Presidency_GMB/status/1268985406965657600] Additionally, in June, students began returning to schools in a limited capacity, with only certain age groups at a time.^[Adama Makasuba June 20th,2020 https://gambiana.com/grade-9-students-to-go-back-to-school-on-june-24/] To this point, The Gambia has implemented policies to slow the spread of the virus, yet amid mounting pressure to resume activity, they must practice caution and refrain from opening too quickly and overburdening the healthcare system. On July 9th, furthering the healthcare-related concerns in the country, healthcare workers on the COVID-19 Rapid Response team announced they would go on strike if they did not receive better pay and conditions.^[Madi Njie and Adama Makasuba July 9th, 2020https://gambiana.com/gambia-health-workers-to-strike-over-pay-and-working-conditions] The workers demand health insurance paid for by the Ministry of Health and more adequate resources provided during shifts.^[Madi Njie and Adama Makasuba July 9th, 2020https://gambiana.com/gambia-health-workers-to-strike-over-pay-and-working-conditions] They plan to “lay down their COVID materials and only do their normal health duties” until they receive fair treatment and compensation.^[Madi Njie and Adama Makasuba Gambiana July 9th, 2020https://gambiana.com/gambia-health-workers-to-strike-over-pay-and-working-conditions/ ]

Providing further tension to the situation, the Gambia Bar Association (GBA) has come out and said they believe the last three declarations of the State of Public Emergency, on June 10th, July 1st, and July 7th, are unconstitutional.^[Arfang M.S. Camara Gambiana July 10th, 2020 https://thepoint.gm/africa/gambia/headlines/state-of-emergency-declarations-not-in-line-with-constitution] The association claims that the Constitution does give President Adama Barrow the power to declare a state of emergency, but does not authorize him to extend it without consulting the National Assembly.^[Arfang M.S. Camara The Point July 10th, 2020 https://thepoint.gm/africa/gambia/headlines/state-of-emergency-declarations-not-in-line-with-constitution] The GBA stated that the state of emergency could only be extended if approved by two-thirds of National Assembly members.^[Arfang M.S. Camara The Point July 10th, 2020 https://thepoint.gm/africa/gambia/headlines/state-of-emergency-declarations-not-in-line-with-constitution] The GBA did not disagree with the policy, rather they urged that the extension should be implemented constitutionally, even during a pandemic. 

The Gambia has been able to keep COVID-19 numbers low as the virus ravages across more developed countries. The coming weeks and months will be crucial for the government to keep measures in place to ensure the safety and awareness of citizens regarding preventative health measures. Additionally, The Gambia must be careful, as bordering Senegal has been hit much harder by the virus with over 8,000 cases.^[WorldOMeter July 14th, 2020 https://www.worldometers.info/coronavirus/country/senegal/] The Gambia and Senegal closed their border on March 23rd to act preemptively to quell the spread of the virus.^[Anadolu Agency March 23rd, 2020 https://www.aa.com.tr/en/africa/covid-19-gambia-senegal-to-close-border-for-21-days/1776298] However, is has been reported that the enforcement of the border crossing is weak, and people move freely across it for weeks at a time without any screening.^[Tumani Baldeh The Point June 23rd, 2020 https://thepoint.gm/africa/gambia/headlines/people-still-move-freely-despite-border-closure] The Gambia will need to slow the spread of the virus while overcoming mounting tensions to begin reopening to avoid overworking the healthcare system and save lives.