---
title: "Pre-lockdown Bangladesh Country Report"
description: Return to [CoronaNet](https://coronanet-project.org/)
author:
  - name: Md. Azmeer Rahman Sorder 
    url: https://www.linkedin.com/in/azmeer-rahman/
    affiliation: University of Dhaka
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>


Bangladesh, a South Asian country neighbored by India and Myanmar, has recently seen a steady increase in COVID-19 cases. The country has a large population of 165 million, making it the 10th most densely populated country in the world. It has a centralized form of government and for administrative and legislative purposes is divided into eight divisions and 64 districts divided between the divisions.^[UNICEF. 2020. https://www.unicef.org/bangladesh/en/where-we-work]  The Awami League political party, led by Prime Minister Sheikh Hasina,^[The Daily Star. December 21st, 2020. https://www.thedailystar.net/politics/awami-league-new-committee-sheikh-hasina-quader-re-elected-1843267] has ruled Bangladesh for more than eleven years.^[BDNews24. January 7th, 2020.  https://bdnews24.com/bangladesh/2020/01/07/hasina-urges-nation-to-keep-faith-in-her-as-government-completes-one-year]  

Government responses to COVID-19 in Bangladesh can be separated into at least three distinct phases:
1. Pre-lockdown measures (January 1st to March 25th),^[Anadolu Agency. March 25th, 2020. https://www.aa.com.tr/en/asia-pacific/bangladesh-imposes-total-lockdown-over-covid-19/1778272] 
2. Lockdown measures (March 26th to May 30th),^[Anadolu Agency. May 14th, 2020. https://www.aa.com.tr/en/asia-pacific/covid-19-bangladesh-extends-lockdown-until-may-30/1840126] and
3. Post lockdown measures (from May 31st).^[New Straits Times. June 1st, 2020. https://www.nst.com.my/world/world/2020/06/596829/despite-surging-covid-19-cases-bangladesh-lifts-lockdown]

This report outlines the Bangladeshi government’s responses to the global COVID-19 crisis, as well as its domestic responses prior to the first nationwide lockdown from March 26th to May 30th.

In mid-January, Bangladesh launched its first public awareness measure about COVID-19, where the Bangladeshi Health Minister announced there was no reason to fear the COVID-19 outbreak in China. The first COVID-19 measure in Bangladesh dates back to January 21st, where screenings of airport arrivals from China were introduced.^[United News of Bangladesh. January 21st, 2020. https://unb.com.bd/category/Bangladesh/coronavirus-outbreak-dhaka-airport-to-screen-passengers-from-china/41933] Due to the prior experience of the Institute of Epidemiology, Disease Control and Research (IEDCR) in dealing with epidemics, on January 26th, the Health Ministry and IEDCR jointly set up a control room to operate COVID-19 screening and manage the epidemic. On January 30th, the Bangladeshi government started preparing temporary quarantine centers in the capital city, Dhaka. 

By the first week of February, Bangladesh started conducting repatriation flights from Wuhan in China for stranded Bangladeshis.^[New Age Bangladesh. February 1st, 2020. https://www.newagebd.net/article/98284/govt-brings-361-back-from-wuhan-early-saturday] To quarantine Wuhan returnees, Bangladesh transformed the Ashkona Hajj Camp,^[The Dhaka Tribune. February 7th, 2020. https://www.dhakatribune.com/bangladesh/2020/02/07/coronavirus-outbreak-how-is-govt-preparing-to-tackle-potential-crisis] a camp for Muslim pilgrims awaiting flights to the Kingdom of Saudi Arabia for pilgrimage. From February 7th, all airports in the country started screening international arrivals, with land and seaports gradually following suit.^[United News of Bangladesh. February 8th, 2020. https://unb.com.bd/category/bangladesh/screening-of-all-flight-passengers-starts-at-dhaka-airport/43651] However, this screening process was mired with great criticism as all screening devices quickly went out of order.^[The Dhaka Tribune, January 30th, 2020. https://www.dhakatribune.com/bangladesh/dhaka/2020/01/30/coronavirus-outbreak-lack-of-staff-equipment-hinder-screening-efforts-at-dhaka-airport] From February 1st, the government imposed restrictions on the entry of Chinese citizens while keeping international travel with the rest of the world intact.^[Anadolu Agency. February 2nd, 2020. https://www.aa.com.tr/en/asia-pacific/bangladesh-suspends-visa-on-arrival-for-china/1721647] In mid-March, an additional entry ban on arrivals from European and Middle Eastern countries was imposed.^[The Business Standard. March 12th, 2020. https://tbsnews.net/economy/aviation/middle-east-bound-passengers-agony-amid-flight-cancellations-55057] 

On February 6th, the Health Ministry and IEDCR launched daily briefings to keep the press and the mass public apprised about the unraveling COVID-19 situation.^[New Age Bangladesh. March 31st, 2020. https://www.newagebd.net/article/103431/what-is-wrong-with-iedcr-briefings] They launched hotlines and increased the number of hotlines as demand rose.^[United News of Bangladesh. February 3rd, 2020. https://unb.com.bd/category/bangladesh/coronavirus-outbreak-iedcr-launches-4-hotline-numbers/43183] Due to its legal and research status, IEDCR emerged as the prime organization to deal with the COVID-19 situation, where the number of calls to IEDCR hotlines steadily increased. Despite IECDR’s limited capability for testing, treatment and quarantine processes, sole responsibility over COVID-19 testing was vested in IEDCR.^[The Dhaka Tribune. March 11th, 2020. https://www.dhakatribune.com/bangladesh/2020/03/11/iedcr-not-expanding-coronavirus-testing-facilities-yet] On March 10th, the authorities asked international travelers to self-quarantine.^[The Daily Star. March 11th, 2020. https://www.thedailystar.net/frontpage/news/self-quarantine-two-weeks-1879000]

To curb misinformation and rumors about COVID-19, the Bangladeshi government and authorities intensified public awareness campaigns through banners and in public gathering areas.^[Health Services Department, March 9th, 2020. https://hsd.gov.bd/sites/default/files/files/hsd.portal.gov.bd/notices/5ebf8903_4c6a_46e9_bb02_280e6c0685f2/Per-1-HSD-20--278.PDF] Along with public awareness campaigns, the government started to sue people under the Digital Security Act, which has been widely condemned for restricting freedom of speech and expression.^[Prothom Alo English. June 20th, 2020. https://en.prothomalo.com/bangladesh/67-cases-filed-under-digital-security-act-since-virus-outbreak-tib]

The Bangladeshi government and ruling party had a longstanding plan to celebrate the birth centennial of “Bangabandhu” Sheikh Mujibur Rahman, Father of the Nation, and to celebrate Mujib Year starting from his birthday, March 17th. This plan had a deep impact on government decisions regarding pandemic management.^[United News of Bangladesh. March 11th, 2020. https://unb.com.bd/category/Politics/govt-busy-with-mujib-year-events-amid-corona-scare-alleges-bnp/46753] Due to low turnout in schools and widespread public outcry, the Ministry of Education shut down schools on March 15th.^[Anadolu Agency. March 16th, 2020. https://www.aa.com.tr/en/asia-pacific/covid-19-bangladesh-shuts-all-educational-institutions/1767425]  Despite public universities seeking to stay open, universities also closed due to boycotts by students who feared infection.^[The New Age. March 16th, 2020. https://www.newagebd.net/article/102355/bangladesh-university-students-boycott-classes-exams] Along with all these setbacks, the government went ahead with the plan to celebrate the birth centennial of the Father of the Nation on March 17th, which involved large crowds and fireworks in Dhaka.^[The Dhaka Tribune. March 17th, 2020. https://www.dhakatribune.com/bangladesh/dhaka/2020/03/17/mujib-year-fireworks-kickoff-celebrations-at-suhrawardy-udyan] As the number of tourists in tourist spots surged, Government imposed a shutdown on tourist spots from March 18th.^[The Business Standard. March 19th, 2020. https://tbsnews.net/coronavirus-chronicle/bangladesh-closes-all-tourist-spots-resorts-amid-coronavirus-fear-58324]  

As the global COVID-19 epicenter shifted from China to Italy, Bangladesh continued to take late action, one of the main reasons being the large number of Bangladeshi immigrants in Italy. Even after the entry ban of flights from several regions, flights from Europe, including Italy, as well as the Middle East continued to arrive,^[The Dhaka Tribune. March 16th, 2020. https://www.dhakatribune.com/bangladesh/dhaka/2020/03/16/defying-bar-european-flight-lands-in-dhaka] and the Ashkona Hajj Camp prepared to quarantine returnees from Italy who failed to maintain quarantine. Subsequently, the managing authority of the Camp was transferred to the Bangladesh Army on March 19th.^[The Daily Star. March 20th, 2020. https://www.thedailystar.net/frontpage/news/dghs-moves-get-1-lakh-test-kits-1883074] The government declared mandatory home quarantine measures for returnees to Bangladesh, which was widely ignored. The government then announced institutional quarantine on March 14th, which was strictly imposed on returnees entering through land ports.^[Prothom Alo English. March 14th, 2020. https://en.prothomalo.com/bangladesh/bangladesh-orders-compulsory-quarantine-for-returnees]

Sadly, both public and private hospitals alike stopped receiving patients unless they possessed a negative COVID-19 test result, resulting in deaths around the country.^[The Daily Star. March 25th, 2020. https://www.thedailystar.net/coronavirus-in-bangladesh-65-year-old-dies-without-treatment-1885714 ; BDNews24. March 19th, 2020. https://bdnews24.com/health/2020/03/19/patients-with-fever-cold-overlooked-in-dhaka-hospitals-amid-coronavirus-fears] As Bangladesh faced acute shortages of medical equipment and hygiene materials, hospitals and almost all health centers providing outpatient services also ceased their service.^[The Financial Express. April 3rd, 2020. https://thefinancialexpress.com.bd/national/private-hospitals-clinics-to-face-punishment-if-remain-closed-1585917587] From March 21st, cases emerged of Bangladeshi doctors who stopped providing services and demanded proper safety gear to perform their duties.^[The Dhaka Tribune. March 21st, 2020. https://www.dhakatribune.com/bangladesh/nation/2020/03/21/health-workers-abstain-from-duties-demand-coronavirus-protection-gear] The authorities decided to ban public visits to hospitals around the country from March 21st.^[The Bangla Tribune English. March 21st, 2020. https://en.banglatribune.com/others/news/91013/Visitors-banned-from-hospitals]

During the ongoing public panic caused by COVID-19, the Bangladesh Election Commission went ahead with by-elections in three constituencies, including one in Dhaka.^[The Business Standard. March 21st, 2020. https://tbsnews.net/bangladesh/politics/5-turnout-dhaka-10-polls-59263 ; The Dhaka Tribune. February 3rd, 2020. https://www.dhakatribune.com/bangladesh/election/2020/02/06/by-polls-in-3-constituencies-on-march-21] On March 21st, the day of election, the Prime Minister announced that no state event for the celebration of Independence Day (March 26th) would be observed.^[The Business Standard. March 21st, 2020.  https://tbsnews.net/bangladesh/govt-cancel-independence-day-programmes-59194]

Instead, the Bangladeshi government announced on March 24th that a national lockdown would be imposed from Independence Day, causing public outcry. In response, at least 10 million people from Dhaka left for their home districts between March 24th to March 26th, hence increasing the risk of infection.^[The Dhaka Tribune. March 28th, 2020. https://www.dhakatribune.com/bangladesh/dhaka/2020/03/28/covid-19-10-million-mobile-subscribers-left-dhaka] As the country went into lockdown from March 26th, the Bangladeshi government announced general holidays for both public and private organizations. Restrictions were imposed on movement before 10am and after 2pm.^[Anadolu Agency. March 25th, 2020. https://www.aa.com.tr/en/asia-pacific/bangladesh-imposes-total-lockdown-over-covid-19/1778272]

As the country started its nationwide lockdown from March 26th, it faced an extreme test to battle the pandemic with a corrupt public sector, weak public health infrastructure, limited resources as well as a very large population. Pre-lockdown government responses included missed opportunities to contain the viral infection, late decision-making and a lack of priority placed on the pandemic. 
