---
title: "Papua New Guinea Country Report"
description: Return to [CoronaNet](https://coronanet-project.org/)
author:
  - name: Lionel Illert
    url: https://www.linkedin.com/in/lionelillert/
    affiliation: Hertie School
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>

Compared to global numbers of COVID-19 cases, Papua New Guinea has relatively been spared. As of May 26th, the country has not reported any coronavirus related deaths. This may have resulted from swift actions taken by the national government or restrictions on tourist and travel activities in the region. Only 8 confirmed cases have been reported since the onset of the global pandemic, with all infections resulting in recoveries.^[World Health Organization. May 26th, 2020. Covid-19 WHO Papua New Guinea. https://covid19.who.int/region/wpro/country/pg] In a country of approximately 9 million, low rates of infection present an optimistic image of the country's attempt to halt the spread of the virus. However, Papua New Guinea's health infrastructure reveals that the country is unprepared to cope with a larger outbreak of the virus.

According to the World Poverty Clock by World Data Lab, roughly 30% of all Papua New Guineans live in extreme poverty.^[World Data Lab. May 26th, 2020. World Poverty Clock. https://worldpoverty.io/headline] These statistics are alarming in a country that fails to meet basic medical requirements and often uses laundry detergent as a disinfectant in medical facilities.^[Fainu, Kalolaine. April 10th, 2020. The Guardian. https://www.theguardian.com/world/2020/apr/11/we-have-nothing-papua-new-guineas-broken-health-system-braces-for-covid-19] This figure is even more dramatic when considering the country has struggled with continuous outbreaks of dengue fever, malaria, drug-resistant tuberculosis, and a recent outbreak of polio. Of the 9 million people in Papua New Guinea, 600-700 of them are doctors, and only 3,000 hospital beds are available for those who can afford them.^[Fainu, Kalolaine. April 29th, 2020. The Guardian. https://www.theguardian.com/world/2020/apr/30/papua-new-guinea-png-health-minister-covid-19-coronavirus-ppe] In November 2019, a new health minister, Jelta Wong, was appointed to fix the fractured and underdeveloped healthcare system by bringing basic health services to the public. 

On March 20th, a few months after the new minister took office, the first confirmed case of COVID-19 was detected from a mining worker from Australia.^[Fainu, Kalolaine. April 29th, 2020. The Guardian. https://www.theguardian.com/world/2020/apr/30/papua-new-guinea-png-health-minister-covid-19-coronavirus-ppe] An Emergency Response Plan of $13 million was budgeted to prepare and respond to the threat of COVID-19^[Radio New Zealand, Papua New Guinea. March 2nd, 2020. Radio New Zealand. https://www.rnz.co.nz/international/pacific-news/410777/png-govt-urges-personal-measures-against-virus-threat], including entry restrictions of travelers from China (specifically Wuhan) and other high-risk areas. Similarly, the land border with Indonesia was closed early on January 30th due to the threat of the virus.^[Radio New Zealand, Papua New Guinea. January 30th, 2020. Radio New Zealand. https://www.rnz.co.nz/international/pacific-news/408486/png-indonesia-land-border-temporarily-closed-due-to-virus-threat] On March 24th, following the first reported infection, the national government headed by Prime Minister James Marape acted swiftly and announced a nationwide state of emergency.^[Radio New Zealand, Papua New Guinea. March 23rd, 2020. Radio New Zealand. https://www.rnz.co.nz/international/pacific-news/412357/coronavirus-png-announces-lockdown-solomons-closes-border-to-non-citizens] The initial announcement grounded all inbound and outbound flights and implemented restrictions on cruise ship operations and large gatherings. The government also declared that travelers who arrived before the lockdown were kept under surveillance and quarantined for 14 days.^[Radio New Zealand, Papua New Guinea. March 17th, 2020. Radio New Zealand. https://www.rnz.co.nz/international/pacific-news/411935/coronavirus-png-opposition-calls-for-state-of-emergency]

Misinformation is a major concern in the country, where witch hunts and torture remain commonplace.^[Staley, Roberta. March 30th, 2019. Post Magazine. https://www.scmp.com/magazines/post-magazine/long-reads/article/3003791/papua-new-guinea-witch-hunts-torture-and-murder] Papua New Guinea is also experiencing high rates of domestic violence against women, a practice likely to be exacerbated under the lockdown.^[Solomon, Ben C.. November 18th, 2018. New York Times. https://www.nytimes.com/2018/11/15/world/asia/papua-new-guinea-apec-women-abuse.html] The Police Commander David Manning announced that anyone spreading false or unofficial information about the virus or the infected online would be arrested and charged under cybercrime laws.^[Loop Papua New Guinea. March 17th, 2020. Loop Papua New Guinea. http://www.looppng.com/png-news/police-prep-covid-19-response-90771] The announcement came as discussions were held on online forums, in which the infected were blamed for the outbreak in the country.^[Radio New Zealand, Papua New Guinea. April 9th, 2020. Radio New Zealand. https://www.rnz.co.nz/international/pacific-news/413924/png-pm-urges-public-not-to-stigmatise-over-covid-19] Another measure to facilitate public awareness and counter misinformation was the establishment of a toll-free number, to field questions from the public surrounding the virus and gather information regarding potential infections in rural areas. 

While the government of Papua New Guinea has acted swiftly to combat the virus and current infections remain low, a close eye should be kept on the country for a potential larger outbreak. Although no new infections have been recorded since the end of April, the poor healthcare infrastructure, lack of safety equipment for hospital personnel, and rampant misinformation remain strong threats against the country’s response to the virus. Additionally, it's uncertain whether new cases in rural and inaccessible regions can be detected and reported successfully. 