---
title: "Bangladesh Post-lockdown Country Report"
description: Return to [CoronaNet](https://coronanet-project.org/)
author:
  - name: Md. Azmeer Rahman Sorder 
    url: https://www.linkedin.com/in/azmeer-rahman/
    affiliation: University of Dhaka 
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>


On May 30th, Bangladesh ended its two-month long nationwide lockdown which had started on March 26th in response to COVID-19.^[Kamaruzzaman, Md. May 14th, 2020. Anadolu Agency. https://www.aa.com.tr/en/asia-pacific/covid-19-bangladesh-extends-lockdown-until-may-30/1840126] Restrictions imposed on public transportation, businesses and almost all public and private organizations respectively were lifted.^[The Business Standard. May 27th, 2020. https://tbsnews.net/coronavirus-chronicle/covid-19-bangladesh/general-holiday-not-extend-further-state-minister-85870] Public transportation was allowed to operate from June 1st.^[United News of Bangladesh. May 31st, 2020. https://unb.com.bd/category/bangladesh/public-transport-to-return-as-lockdown-ends-with-virus-firmly-entrenched/52306] Private businesses and all other public and private activities were provided with a detailed set of instructions and guidelines to follow.^[Islam, Shahidul. May 27th, 2020. BDNews 24. https://bdnews24.com/bangladesh/2020/05/27/bangladesh-leaving-lockdown-as-offices-public-transports-to-reopen-from-may-31] But while the country emerged out of lockdown, the ensuing scenario forced the authorities to impose fresh lockdown measures in parts of the country.^[Mamun, Shohel and Shawon, Ali Asif. June 9th, 2020. The Dhaka Tribune. https://www.dhakatribune.com/health/coronavirus/2020/06/09/bangladesh-set-to-test-zone-wise-lockdown-from-tuesday-night] 

As Bangladesh came out of its lockdown in June, the country witnessed some of the highest numbers of officially detected cases as well as high testing numbers and a high volume of deaths.^[Kamaruzzaman, Md. June 9th, 2020. Anandolu Agency. https://www.aa.com.tr/en/asia-pacific/bangladesh-records-highest-daily-covid-19-deaths-cases/1870617]  COVID-19 cases in some major areas in Bangladesh rose sharply and very quickly.^[The Economist. June 6th, 2020. https://www.economist.com/asia/2020/06/06/covid-19-infections-are-rising-fast-in-bangladesh-india-and-pakistan] In response, the Bangladeshi government soon decided to impose a new lockdown in most COVID-19 affected regions,^[The Financial Express. June 6th, 2020. https://thefinancialexpress.com.bd/national/govt-to-place-covid-19-hotspots-under-lockdown-1591448727] where the authorities classified the whole country into three zones - red, yellow and green.^[Zihad, Shamsul Huq. June 7th, 2020. The Financial Express.  https://thefinancialexpress.com.bd/views/of-colour-coded-zones-and-lockdown-1591546650] Although the government decided to impose lockdown again, including formal lockdown in the red zones, the authority tasked with classifying localities took an extended amount of time to formulate the colored zone map.^[The Business Standard. June 19th, 2020. https://tbsnews.net/coronavirus-chronicle/covid-19-bangladesh/criticism-grows-zoning-lockdown-not-yet-finalised-95326] Along with this, the government decided to impose a “trial” lockdown in Dhaka.^[The Daily Star. June 9th, 2020. https://www.thedailystar.net/backpage/news/east-rajabazar-trial-lockdown-midnight-1911325] The lockdown in Dhaka was also plagued with administrative gridlock as the red zone map took time to be finalized.^[Chowdhury, Zia. June 15th, 2020. The Business Standard. https://tbsnews.net/coronavirus-chronicle/covid-19-bangladesh/city-corporations-seek-more-specific-maps-red-zone] The lockdown in the red zones was imposed from mid/late-June to late July.^[United News of Bangladesh. June 22nd, 2020. https://unb.com.bd/category/bangladesh/red-zones-imposed-with-general-holiday-in-parts-of-10-districts/53436] Since the “trial” lockdown initiative lasted until late July, Bangladesh as of September 1st is yet to witness any additional lockdown in any other areas.^[The Daily Star. July 25th, 2020. https://www.thedailystar.net/city/news/coronavirus-outbreak-lockdown-wari-lifted-1935789] 

From June 1st, public transportation was allowed to operate with 50% occupancy and with a 60% increase to the original fare.^[The Business Standard. May 31st, 2020. https://tbsnews.net/bangladesh/road-transport/govt-increases-bus-fares-60-87037] ^[The Business Standard. June 1st, 2020. https://tbsnews.net/bangladesh/road-transport/public-transport-allowed-not-uber-pathao-87532] ^[United News of Bangladesh. May 31st, 2020. https://unb.com.bd/category/Bangladesh/govt-increases-bus-fares-by-60-pc/52327] However, this initiative proved futile as the transportation services quickly ignored the mandatory measures.^[The Business Standard. June 2nd, 2020. https://tbsnews.net/bangladesh/road-transport/health-guidelines-take-back-seat-public-transportation-87928] These services ignored all the health guidelines, as well as the rules for 50% occupancy and a 60% fare increase.^[The New Age BD. June 16th, 2020. https://www.newagebd.net/article/108485/violation-of-health-guidelines-in-public-transports-must-be-stopped] The authorities conducted a few random enforcement drives but ultimately failed to regulate, ensure and enforce its public transportation directives.^[The Financial Express. June 8th, 2020. https://thefinancialexpress.com.bd/national/dmp-fines-shop-owners-buses-for-violating-health-guidelines-1591595551] Unlike other countries, ride-sharing services were not allowed to operate with the national easing of lockdown.^[The Business Standard. June 1st, 2020. https://tbsnews.net/bangladesh/road-transport/public-transport-allowed-not-uber-pathao-87532]  Four-wheeled vehicles were permitted to operate from June 21st and two-wheeled vehicles were permitted on road from September.^[The Daily Star. September 5th, 2020. https://www.thedailystar.net/city/news/bikes-allowed-ply-again-1956137] ^[The Financial Express. June 21st, 2020. https://www.thefinancialexpress.com.bd/trade/govt-allows-ride-sharing-services-except-motorbikes-1592746558] The occupancy and fare rule was withdrawn with effect from September 1st.^[The Daily Star. August 29th, 2020. https://www.thedailystar.net/bangladesh-previous-bus-fare-be-reinstated-september-1-1952853] From June 1st, domestic flights were also allowed to operate.^[Hasan, Rashidul. May 29th, 2020. The Daily Star. https://www.thedailystar.net/city/news/domestic-flights-resume-june-1-1906126]  However, the ban on international flights continued until June 15th.^[The Daily Star. June 11th, 2020. https://www.thedailystar.net/caab-resume-international-flights-from-june-16-1912645] Along with the continuation of international flight, Bangladesh suspended its visa-on-arrival services for all countries except foreign investors and foreign businessmen from June 16th.^[The Business Standard. June 17th, 2020. https://tbsnews.net/bangladesh/bangladesh-bans-visas-arrival-indefinitely-94366] 

Restrictions on movement in Bangladesh were set from the nationwide lockdown period between 8pm to 6am.^[Kamruzzaman, Md. May 4th, 2020. Anadolu Agency. https://www.aa.com.tr/en/asia-pacific/bangladesh-imposes-new-restrictions-on-public-movement/1828684] From July 1st, movement restrictions were limited to between 10 pm and 5am,^[Cabinet Division of People’s Republic of Bangladesh. June 30th, 2020. https://cabinet.gov.bd/sites/default/files/files/cabinet.portal.gov.bd/notices/437be9f1_fcdd_4e3d_b5ce_fb8242275e10/123.pdf]  and extended until August 31st.^[The Business Standard. August 3rd, 2020. https://tbsnews.net/bangladesh/restriction-public-movements-extended-till-aug-31-114871] Since the authorities did not extend the restriction beyond August 31st, free movement of citizens was legally allowed for 24 hours uninterrupted.^[Adhikary, Tuhin Shubhra and Bin Habib, Wasim. September 1st, 2020. The Daily Star. https://www.thedailystar.net/frontpage/news/curbs-public-movement-go-1953769] From June 4th, Bangladesh rolled out a contact tracing app on a trial basis.^[The Daily Star. June 5th, 2020. https://www.thedailystar.net/business/telecom/news/bangladesh-finally-gets-its-own-contact-tracing-app-1909309] On July 21st, the authorities imposed a mandatory mask wearing policy in all the offices and public spaces.^[The Daily Star. July 22nd, 2020. https://www.thedailystar.net/frontpage/news/wearing-mask-now-mandatory-outdoors-1934241]  Despite these guidelines and administrative measures, cooperation from citizens remained very low.^[The Financial Express. July 28th, 2020. https://thefinancialexpress.com.bd/health/mask-wearing-mandatory-in-bd-not-everyone-cares-1595928041] 

In response to COVID-19, Bangladesh went ahead and increased the number of doctors and nurses in its medical workforce.^[United News of Bangladesh. June 29th, 2020. https://unb.com.bd/category/bangladesh/govt-to-recruit-2000-doctors-4000-nurses-pm/53847]  However, one of most damaging policies taken by Bangladesh government was to set a price for COVID-19 testing in state-run hospitals on June 28th. While testing had initially been free of charge,^[Hasan, Kamrul. The Dhaka Tribune. June 29th, 2020. https://www.dhakatribune.com/bangladesh/2020/06/29/health-ministry-fixes-covid-19-test-fees-at-tk200-tk500] the government stated that unnecessary testing was the rationale behind the introduction of the new policy.^[The Dhaka Tribune. July 8th, 2020. https://www.dhakatribune.com/bangladesh/2020/07/08/tib-to-govt-withdraw-suicidal-decision-to-charge-for-covid-19-test-at-state-run-facilities] While this imposed fee was reduced later in August 19th,^[The Business Standard. August 20th, 2020. https://tbsnews.net/coronavirus-chronicle/covid-19-bangladesh/govt-reduces-covid-19-test-fees-121984] private hospitals continued to charge for COVID-19 testing and treatment due to a lack of government regulations.^[The Dhaka Tribune. June 21st, 2020. https://www.dhakatribune.com/health/coronavirus/2020/06/21/high-cost-of-covid-19-test-at-private-hospitals-raises-concern] This caused private hospitals to charge unreasonably high prices for their services without repercussion.^[Rahman, Mizanur. The Dhaka Tribune. July 13th, 2020. https://www.dhakatribune.com/health/coronavirus/2020/07/13/private-hospitals-charging-patients-arbitrarily-for-covid-19-treatment] Another damaging policy taken by Bangladesh was the termination of the daily COVID-19 briefing by the Directorate General of Health Services on August 11th.^[United News of Bangladesh. August 11th, 2020. http://unb.com.bd/category/bangladesh/no-more-daily-briefing-on-covid-19-situation-from-wednesday-dghs/55856] Experts feared such measure would hurt the country’s progress against the pandemic.^[Hasan, Kamrul. The Dhaka Tribune. June 28th, 2020. https://www.dhakatribune.com/health/coronavirus/2020/06/28/experts-this-is-not-the-time-to-charge-people-for-covid-19-tests]  

In July, Bangladesh’s COVID-19 pandemic management took a major blow. On July 6th, Bangladeshi passengers to Italy were found with fake COVID-19 negative certificates and on July 7th, Italy suspended flights from Bangladesh for initially one week.^[The Observer BD. July 8th, 2020. https://www.observerbd.com/details.php?id=264568] ^[The Business Standard. July 7th, 2020. https://tbsnews.net/economy/aviation/covid-19-italy-suspends-flights-bangladesh-one-week-103096]  Later, the Italian government slapped a three month travel ban on Bangladeshis.^[Seckin, Baris. July 16th, 2020. Anadolu Agency. https://www.aa.com.tr/en/europe/italy-imposes-travel-ban-on-3-more-balkan-nations/1912821] In response, Bangladesh law enforcement authorities launched several drives only to uncover a huge trope of irregularities and corruptions in the health sector.^[Gettleman, Jeffery and Yasir, Sameer. New York Times. July 16th, 2020. https://www.nytimes.com/2020/07/16/world/asia/coronavirus-bangladesh-italy-certificates.html] ^[Hossain, Shakhawat. The New Age BD. July 21st, 2020. https://www.newagebd.net/article/111693/public-deals-on-political-consideration-backfires]  Consequently, several health sector individuals were arrested.^[Al Jazeera. July 16th, 2020. https://www.aljazeera.com/news/2020/07/bangladesh-arrests-hospital-owner-fake-coronavirus-results-200716033249660.html] ^[The Daily Star. July 12th, 2020. https://www.thedailystar.net/fake-covid-19-certificates-jkg-health-care-chairman-dr-sabrina-arrested-1929117] Bangladesh, as damage control, imposed restrictions to prevent people leaving Bangladesh without a COVID-19 negative certificate.^[The Daily Star. July 12th, 2020. https://www.thedailystar.net/country/news/no-bangladeshi-can-leave-country-without-valid-covid-19-negative-certificate-govt-1929261] The restrictions were also eased by the end of July.^[United News of Bangladesh. July 30th, 2020. https://unb.com.bd/category/Bangladesh/corona-negative-report-not-compulsory-for-all-foreign-bound-passengers-minister/55399]  

Another case of corruption brought fresh criticism when the food bill of doctors and nurses employed in Dhaka Medical College was reported as 200 million Bangladeshi Takas.^[The New Age BD. June 30th, 2020. https://www.newagebd.net/article/109830/tk-20cr-bill-for-food-cost-of-doctors-nurses-being-probed-pm] Transparency International Bangladesh, an international anti-corruption agency, also published reports on June 15th which cited corruption in purchases of the medical equipment during the pandemic.^[The New Age BD. June 16th, 2020. https://www.newagebd.net/article/108515/tib-finds-gross-corruption-in-covid-19-purchases] Due to their appropriation of relief intended for distribution during the pandemic to the disadvantaged, elected public officials were continuously fired.^[The Financial Express. June 2nd, 2020. https://thefinancialexpress.com.bd/national/relief-scam-85-public-representatives-face-suspension-so-far-1591116888] For example, the Local Government Division had fired 100 elected public officials by June 17th.^[United News of Bangladesh. June 17th, 2020. https://unb.com.bd/category/Bangladesh/relief-embezzlement-100-public-representatives-suspended-so-far/53202]  

Instead of reopening like other organizations, educational institutions were not subject to the easing of restrictions.^[United News of Bangladesh. May 27th, 2020. https://unb.com.bd/category/Bangladesh/educational-institutions-to-remain-shut-till-june-15/52155] Hafizia Madrasas, which are Islamic religious schools that teach the Quran and are not registered with any regulating authorities, however were allowed to open from July 12th.^[Prothom Alo English. July 9th, 2020. https://en.prothomalo.com/youth/education/hafizia-madrasas-to-reopen-from-12-july] The restrictions on other kind of Madrasas remained intact until August 24th. Qawmi Madrasas, which are Islamic higher education schools, decided to open from August 8th despite the government mandated closures.^[Hossain, Chowdhury Akbar. July 23rd, 2020. The Dhaka Tribune. https://www.dhakatribune.com/bangladesh/education/2020/07/23/qawmi-madrasa-body-announces-reopening-from-august-8-defying-govt-decision] From August 24th, Qawmi Madrasas were finally allowed to open, while restrictions on other educational institutions were extended to October 3rd.^[The Business Standard. August 27th, 2020. https://tbsnews.net/bangladesh/education/educational-institutions-closure-further-extended-till-oct-3-124924] ^[The Dhaka Tribune. August 24th, 2020. https://www.dhakatribune.com/bangladesh/education/2020/08/24/qawmi-madrasas-cleared-to-reopen-amid-pandemic] On August 25th and August 27th, Bangladesh cancelled its two sets of public exams for 5th graders and 8th graders respectively.^[Abdullah, Mamun. August 27th, 2020. The Dhaka Tribune. https://www.dhakatribune.com/bangladesh/2020/08/27/no-jsc-jdc-exams-this-year] ^[Abdullah, Mamun. August 25th, 2020. The Dhaka Tribune. https://www.dhakatribune.com/bangladesh/education/2020/08/25/no-pec-exams-this-year]   

Bangladesh observed Eid-al-Adha on August 1st,^[The Daily Star. July 22nd, 2020. https://www.thedailystar.net/frontpage/news/eid-ul-azha-august-1-1934213]  which involves the Muslim population engaging in rituals involving animal sacrifice.^[Encyclopedia Britanicca. 2020. https://www.britannica.com/topic/Eid-al-Adha] As a result, the demand for sacrificial animals rises higher than anytime of the year.^[Siddiquee, Muhammad Nurul Amin. July 10th, 2020. The Financial Express. https://thefinancialexpress.com.bd/views/views/eid-cattle-markets-during-pandemic-a-six-point-guideline-1594392852] The restrictions on religious mass congregation in open spaces were similar to the Eid-al-Fitr restrictions in May.^[Sakib, SM Nazmus. July 12th, 2020. Anadolu Agency. https://www.aa.com.tr/en/asia-pacific/bangladesh-restricts-public-eid-prayers-amid-pandemic/1908129] As part of Eid-al-Adha, the Bangladeshi government permitted cattle markets despite having high potential of becoming virus transmission hubs.^[Syfullah, Muhammad. July 10th, 2020. United News of Bangladesh. https://unb.com.bd/category/Special/experts-fear-spike-in-corona-infections-after-eid-ul-azha/54393] ^[Somoy News English. July 13th, 2020. https://en.somoynews.tv/9740/news/Govt-decides-to-permit-cattle-markets-despite-pandemic] The authorities’ announcement to maintain social distancing and other health measures inside cattle markets were totally ignored by the mass population.^[Sagor, Al Mamun. July 19th, 2020. United News of Bangladesh. https://unb.com.bd/category/Special/huge-farmers-flock-to-kushtia-cattle-haat-defying-corona-safety-restrictions/54861] ^[Hossain, Sohrab. July 27th, 2020. The Daily Star. https://www.thedailystar.net/country/news/coronavirus-crowded-cattle-markets-pose-risk-health-rules-grossly-ignored-1936877] Brahmanbaria district, which had earned notoriety for arranging a funeral with about one hundred thousand people in April, repeated a similar scenario on August 10th with thousands of people.^[BDNews24. August 10th, 2020. https://bdnews24.com/bangladesh/2020/08/10/thousands-defy-coronavirus-health-rules-at-brahmabaria-funeral-again]

On June 21st, the People’s Republic of China declared that Bangladesh would get priority in receiving a COVID-19 vaccine from them.^[The Business Standard. June 21st, 2020. https://tbsnews.net/coronavirus-chronicle/covid-19-bangladesh/covid-19-vaccine-bangladesh-get-priority-if-china-develops] On July 19th, China announced that they were going to start their Phase 3 trial for the Sinovac vaccine in Bangladesh.^[The Business Standard. July 19th, 2020. https://tbsnews.net/coronavirus-chronicle/covid-19-bangladesh/bmrc-approves-chinese-covid-19-vaccine-trial-bangladesh] Soon after the announcement, the vaccine trial was delayed, citing delay in decision making on Bangladesh’s part.^[United News of Bangladesh. August 12th, 2020. https://unb.com.bd/category/bangladesh/decision-on-collecting-covid-vaccine-human-trial-of-chinese-shot-soon-minister/55910] Bangladesh finally approved Chinese vaccine trial on August 27th.^[Paul, Ruma. August 27th, 2020. Reuters. https://www.reuters.com/article/us-health-coronavirus-bangladesh-china/bangladesh-approves-late-stage-trial-of-chinas-sinovac-covid-19-vaccine-candidate-idUSKBN25N2ER] The visit of Indian foreign secretary came with the announcement that Bangladesh would get a COVID-19 vaccine on a priority basis from India.^[Bhattacherjee, Kallol. August 19th, 2020. The Hindu. https://www.thehindu.com/news/national/india-to-offer-covid-19-vaccine-to-bangladesh-on-priority-basis/article32395700.ece] The country also announced a clinical trial of the anti-parasitic drug, Ivermectin, from June 17th,^[The Financial Express. June 17th, 2020. https://thefinancialexpress.com.bd/national/icddrb-begins-clinical-trial-of-ivermectin-for-covid-19-patients-1592412705] and the authorities decided to start using tuberculosis detection machines, GeneXpert, to test the samples from June 24th.^[Molla, Mohammad Al-Masum. The Daily Star. June 30th, 2020. https://www.thedailystar.net/frontpage/news/alternative-way-trace-covid-19-1922637] On June 9th, the country launched its own plasma bank.^[United News of Bangladesh. June 9th, 2020. https://unb.com.bd/category/bangladesh/plasma-network-shohojoddha-launched/52808] While daily testing rose to its highest by the time the country came out of lockdown in June,^[The Business Standard. June 10th, 2020. https://tbsnews.net/coronavirus-chronicle/covid-19-bangladesh/covid-19-death-toll-crosses-1000-mark-bangladesh-91252] with time, the testing number came down after this.^[Sakib, SM Nazmus. July 10th, 2020. Anadolu Agency. https://www.aa.com.tr/en/asia-pacific/bangladesh-covid-19-sample-testing-falls-sharply/1906190]  By the end of August, Bangladesh was testing far less than the recommended level.^[Cousins, Sophie. August 29th, 2020. The Lancet. https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)31819-5/fulltext]  

As Bangladesh came out of its nationwide lockdown, it placed restrictions on up to 25% employees in public offices from June 1st.^[Islam, Shahidul. June 1st, 2020. BDNews24. https://bdnews24.com/bangladesh/2020/06/01/bangladesh-restricts-presence-of-govt-employees-in-offices-in-pandemic] On August 6th, the reduced attendance policy in the public offices was withdrawn, with these offices starting to function with their usual number of employees from August 9th.^[  Prothom Alo. August 6th, 2020. https://www.prothomalo.com/bangladesh/%E0%A7%A8%E0%A7%AB-%E0%A6%B6%E0%A6%A4%E0%A6%BE%E0%A6%82%E0%A6%B6%E0%A7%87%E0%A6%B0-%E0%A6%A8%E0%A6%BF%E0%A7%9F%E0%A6%AE-%E0%A6%AC%E0%A6%BE%E0%A6%A4%E0%A6%BF%E0%A6%B2-%E0%A6%85%E0%A6%AB%E0%A6%BF%E0%A6%B8-%E0%A6%86%E0%A6%B8%E0%A6%A4%E0%A7%87-%E0%A6%B9%E0%A6%AC%E0%A7%87-%E0%A6%B8%E0%A6%AC%E0%A6%BE%E0%A6%87%E0%A6%95%E0%A7%87] The closure of the Lower Court extended beyond May 30th.^[The Daily Star. June 10th, 2020. https://www.thedailystar.net/supreme-courts-appellate-division-run-virtual-functions-till-june-30-1912045] However, all courts in the country, except the Supreme Court, restarted their full functions from August 5th.^[BDNews24. July 31st, 2020. https://bdnews24.com/bangladesh/2020/07/31/bangladesh-lower-courts-to-return-to-normal-proceedings-on-aug-5] Bangladesh also allowed tourist spots to operate from August 18th.^[The Independent BD. August 16th, 2020. http://www.theindependentbd.com/post/251728]  

Bangladesh’s post-lockdown policies, which spanned from June to August, mark a gradual relaxing of existing restrictive measures. The policies include sporadic positive policies lacking in necessary enforcement, the end of arguably crucial policies and repeated adherence to popular religious sentiment. 
