---
title: "Region 7 United States Research Note"
description: Return to [CoronaNet](https://coronanet-project.org/)
author:
  - name: Shiva Teerdhala
    url: https://www.linkedin.com/in/shiva-teerdhala-04a792198/
    affiliation: University of Pennsylvania "(Wharton School of Business)"
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>

As of March 26th, the United States of America became the epicenter of the COVID-19 crisis, surpassing Italy for the distinction of the most coronavirus cases in the world.^[Rettner, Rachael. March 26, 2020. LiveScience. https://www.livescience.com/us-coronavirus-cases-surpass-china.html] Unlike many other countries, the U.S. policy response has been decentralized, with each state largely left to its own devices. The federal government provided economic and infrastructural support but no centralized lockdown or containment policy. Due to this state-level response, a striking heterogeneity of policy and policy timing has developed across the country, making regional policy trends much more visible than those seen on a national scale. This report investigates the policies implemented in the Midwestern states of Iowa, Missouri, Kansas, and Nebraska (Department of Health and Human Services Region 7), which maintain large rural populations and a long tradition of local governance.^[Department of Health and Human Services. April 15, 2014. https://www.hhs.gov/about/agencies/iea/regional-offices/index.html] These states’ policies are all centered around maintaining local independence, taking rural regions into account, and reopening the economy as soon as possible. 

The four Region 7 states issued health restrictions much later than other regions of the country. Kansas Governor Laura Kelly was the first to deliver a stay-at-home order on March 30th, simultaneously mandating 6 feet social distancing and banning gatherings of ten or more individuals.^[Treisman, Rachel. June 24, 2020. National Public Radio (NPR) https://www.npr.org/847413697] Missouri followed a week later, issuing an identical policy on April 6th.^[Treisman, Rachel. June 24, 2020. National Public Radio (NPR) https://www.npr.org/847413697] Iowa, on the other hand, never enacted a stay-at-home order, with Republican Governor Kim Reynolds opting for a less sweeping approach and identifying individual businesses to shut down. In the state, restaurants closed on March 17th, personal grooming facilities closed a week later, and amusement parks, libraries, and malls finally closed on April 6th.^[Norvell, Kim. Pfannenstiel, Brianne. April 6, 2020. De Moines Register. https://www.desmoinesregister.com/story/news/2020/04/07/iowa-equivalent-stay-at-home-order-coronavirus-kim-reynolds/2961810001/] Iowan officials reasoned that its majority rural population did not necessarily require the same strict policies as neighboring Missouri, a more urban state containing the two major cities of St. Louis and Kansas City. This rural-urban divide is further emphasized by largely rural Nebraska, which also declined to implement a statewide stay-at-home order. Governor Pete Ricketts instead issued “directed health measures” on a county-by-county basis beginning in late March, ostensibly to preserve his state’s dedication to rural populations and county-level governance.^[Cordes, Henry J. April 11, 2020. Omaha World-Herald. https://www.omaha.com/news/state_and_regional/no-stay-at-home-order-nebraska-still-rates-well-in-coronavirus-cases-and-deaths/article_78b97ca4-bae5-57c7-b4f7-818530800207.html] These measures, which included social distancing, quarantine, and mass gathering restrictions similar to the other Region 7 states, were declared by Dr. Anthony Fauci of The National Institute of Allergies and Infectious Diseases (NIAID) to be functionally equivalent to a stay-at-home order.^[Nebraska TV. April 6, 2020. https://nebraska.tv/news/local/fauci-nebraskas-coronavirus-plan-functionally-equivalent-to-stay-at-home-order] Although these states’ policies are in line with national recommendations, their delayed timings stand out when compared to their other Midwestern peers. Directly east of HHS Region 7 are Illinois, Indiana, and Ohio, which implemented stricter stay-at-home orders nearly a week earlier. Furthermore, unlike the Region 7 states, Illinois, Indiana, and Ohio led the nation with the preventative nature of their COVID-19 response. For example, Ohio Governor Mike DeWine was one of the first to close down restaurants, bars, and recreational facilities in early March.^[British Broadcasting Corporation. April 1, 2020. https://www.bbc.com/news/world-us-canada-52113186]

Despite Region 7’s initially delayed response, its states mostly followed similar reopening plans, all of which embodied the ideal of local independence to varying degrees. All four states organized their reopening in phases of progressively looser restrictions. Iowa was the first state to begin reopening, starting Phase 1 on May 1st. During this phase, businesses opened with 50% maximum occupancy, mandatory social distancing, and sanitation measures in 77 of Iowa’s 99 counties, while the other 22 opted to continue under stricter public health guidance.^[Office of the Governor of Iowa. April 27, 2020. https://governor.iowa.gov/press-release/gov-reynolds-signs-new-proclamation-continuing-the-state-public-health-emergency-0?fbclid=IwAR0NpWOiSYrYes_rfvRtrI9FyF_yPU4waNogA1ebec7xlUCEDWwPM-r__BY] Nebraska also epitomized this approach, with Governor Pete Ricketts rolling back his directed health measures based on the COVID-19 situation in each county. Thus, sparsely populated areas of the state saw the partial reopening of restaurants and personal grooming services; in contrast, hard-hit urban centers in Lancaster, Hall, and Dawson counties initially had no restrictions removed.^[Hammel, Paul. Stoddard, Martha. Anderson, Julie. April 25, 2020. Omaha World-Herald. https://www.omaha.com/news/state_and_regional/ricketts-easing-nebraska-coronavirus-restrictions-as-of-may-4-limited-reopening-of-economy/article_2abb7fce-5ca5-54d8-8ab0-1b968ff2aa1a.html] Missouri and Kansas followed suit on May 4th, with their Phase 1 reopening, lifting their statewide stay-at-home orders and allowing businesses to open with limited occupancy and mandatory 6 feet social distancing measures. Both reopening plans served as “regulatory baselines” — that is, the state government allowed county health officials to implement stricter restrictions if deemed necessary.^[Missouri Governor Michael L. Parson. April 3, 2020. https://governor.mo.gov/press-releases/archive/governor-parson-issues-statewide-stay-home-missouri-order-control-contain; Office of the Governor of Kansas. May 26, 2020. https://www.coronavirus.kdheks.gov/DocumentCenter/View/1057/Plan-to-Reopen-Kansas-Framework-PDF---Full-Plan---5--26-20] The region’s early and locally-directed reopening poses a striking contrast to the rest of the country. For example, New York state’s reopening occurred much later, beginning Phase 1 in late May, involving strict guidance from the state government.^[Governor Andrew M. Cuomo. May 26, 2020. https://www.governor.ny.gov/news/amid-ongoing-covid-19-pandemic-governor-cuomo-announces-eighth-region-hits-benchmark-begin]

Once Region 7 began reopening, it quickly progressed towards completing the process. Iowa continued to Phase 2 in mid-May, with all 99 counties opened for business under loosened regulations and operated without occupancy guidelines by June 12th.^[Office of the Governor of Iowa. June 10, 2020. https://governor.iowa.gov/press-release/gov-reynolds-signs-new-proclamation-continuing-the-state-public-health-emergency-5] Likewise, Missouri completed its two-phase reopening in mid-June — in the words of Governor Mike Parson, “there [is] no statewide public health order… Missouri will be fully open for business.”^[Missouri Governor Michael L. Parson. N.d. https://governor.mo.gov/show-me-strong-recovery-plan-guidance-and-frequently-asked-questions] Nebraska is continuing its targeted reopening, with no restrictions as of June 22nd in 89 rural counties, while urban areas are continuing with the slower reopening.^[Hammel, Paul. May 22, 2020. Omaha World-Herald. https://www.omaha.com/news/state_and_regional/ricketts-seeks-balance-as-he-reopens-nebraska-bars-and-loosens-limits-on-public-gatherings/article_defc4172-36c7-5f02-9cce-39214dc54437.html] Along the same lines, Kansas Governor Laura Kelley devolved even more authority to local executives, changing the state’s reopening mandates to voluntary guidelines; counties will now reopen on an individual basis, similar to the situation in Nebraska.^[Beckman, Wyatt, et al. June 19, 2020. Kansas Health Institute. https://www.khi.org/announcements/article/20-25] 

Region 7’s blend of local governance and a high proportion of rural counties has created policy responses to COVID-19 centered around resuming activity as quickly as possible. As one of the first reopened regions in the United States, these states could serve as future policy models for other states if they manage to avoid a new surge in cases. Unfortunately, regions of the country that reopened at the same time, such as the Southern U.S., are rapidly emerging as epicenters of COVID-19. Florida, Texas, and Arizona have seen record-breaking case increases for the past several days, with Florida reporting 4,049 new cases on June 20th — the most in a single day.^[Maxouris, Christina. Levenson, Eric. June 22, 2020. CNN. https://www.cnn.com/2020/06/22/health/us-coronavirus-monday/index.html] If the pandemic continues its path through reopened areas and spreads in full force to Region 7, Missouri, Kansas, Iowa, and Nebraska may instead be viewed by history as case studies of states that reopened too soon. 