---
title: "Solomon Islands Country Report"
description: Return to [CoronaNet](https://coronanet-project.org/)
author:
  - name: Ankita Mohan
    url: https://www.linkedin.com/in/ankita-mohan-888102113/
    affiliation: College of William & Mary 
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>

The Solomon Islands is a country located to the southeast of Papua New Guinea, made up of six islands with a population of 600,000 people.^[British Broadcasting Corporation. n.d. BBC. https://www.bbc.com/news/world-asia-15896396] As the COVID-19 pandemic remains a global health crisis, the Solomon Islands national government has been taking measures to prevent the spread of COVID-19 since the onset of the public health threat. With the first known case reported on December 31st in China, the Solomon Islands National Government was quick to advise citizens to practice good hygiene and wear a face mask in early February.^[GardaWorld. February 6, 2020. GardaWorld. https://www.garda.com/crisis24/news-alerts/311906/solomon-islands-authorities-implement-entry-restrictions-due-to-2019-ncov-outbreak-february-1] As the virus began to increase in force, the Solomon Islands responded accordingly. On March 11th, the World Health Organization announced that COVID-19 was a global pandemic, and on March 25th, the Solomon Islands declared a state of emergency. The declaration was extended until July 25th, to ensure the proper handling of the pandemic.^[Ride, Anouk and Keka, Georgina. June 5, 2020. Asia & The Pacific Policy Society https://www.policyforum.net/together-or-apart-against-covid-19-the-solomon-islands-state-of-emergency/]

However, the threat of COVID-19 added to the other struggles on the Solomon Islands. With the overcrowded land with poor sanitation and ill-equipped medical institutions, the islands already struggle with other illnesses. The risk of COVID-19 has brought a newfound fear that has incited other precautions.^[Wilson, Catherine. April 3, 2020. Aljazeera. https://www.aljazeera.com/news/2020/04/remote-pacific-islands-prepare-worst-coronavirus-looms-200403045004961.html] The country implemented lockdown exercises to test the islands' ability to react to a potential virus outbreak. During the two days of the lockdown, the government enforced the policies with fines and jail time.^[WorldAware. May 18, 2020. WorldAware. https://www.worldaware.com/covid-19-alert-honiara-solomon-islands-enforcing-36-hour-lockdown-police-may-20-22] Even so, not all citizens complied with the lockdown, and there were more than 20 arrests during the simulation.^[Wasuka, Evan. May 22, 2020. ABC. https://www.abc.net.au/radio-australia/programs/pacificbeat/more-than-20-arrested-as-honiara-lockdown-ends/12274856]

When considering the economic effects of the pandemic, the results are not proportional. Many markets in the country were regulated on a case by case basis, leaving some markets more crowded due to the closures. Public transportation was left unmonitored, and many bars and casinos operated without restrictions.^[GardaWorld. February 6, 2020. GardaWorld. https://www.garda.com/crisis24/news-alerts/311906/solomon-islands-authorities-implement-entry-restrictions-due-to-2019-ncov-outbreak-february-1] 

Additionally, the government has been monitoring public dissent. On March 31st, the Ministry of Health announced that they would terminate staff who criticized the COVID-19 response of the country. Dr. Claude Posala, the president of the Solomon Islands Medical Association, was fired for his criticism of the government response to the virus during the state of emergency. Dr. Posala reportedly posted false information and internal government documents which had elicited public outrage towards the government.^[Civicus. June 9, 2020. Civicus. https://monitor.civicus.org/updates/2020/06/09/critical-voices-silenced-solomon-islands-amid-pandemic/]

Governor-General David Vunagi admits that the Solomon Islands will only be safe if COVID-19 does not enter the country, attesting to the poor health infrastructure existing on the islands.^[Kekea, Georgina. March 25, 2020. Solomon Times. https://www.solomontimes.com/news/governor-general-declare-state-of-public-emergency-in-solomon-islands/9655 ] Initially, due to a lack of health resources to test samples of COVID-19, the government had to send samples to other countries that had resources and could confirm the existence of the virus. However, in late April, China donated a Real-Time PCR machine, which allowed for the testing of COVID-19 in the country.^[RNZ. April 27, 2020. RNZ. https://www.rnz.co.nz/international/pacific-news/415197/solomons-has-capability-to-test-for-covid-19-in-country] Due to the inadequate public health infrastructure, as of June 6th, there have been only 17 COVID-19 tests administered. However, all tests have come back negative.^[RNZ. June 6, 2020. RNZ. https://www.rnz.co.nz/international/pacific-news/418420/solomons-local-covid-19-tests-return-negative] 

The Solomon Islands is taking steps to better the existing weak health infrastructure. To better assist the Solomon Islands in policy and health care responses, the country has received aid from outside sources. Initially, in early April, the Asian Development Bank (ADB) had assisted the disaster response with 6 million USD in aid money.^[Devdiscourse. June 25, 2020. Devdiscourse. https://www.devdiscourse.com/article/business/1105315-adb-approves-20m-to-help-solomon-islands-combat-covid-19-and-impact-on-economy] On June 1st, the International Monetary Fund awarded a 28.5 million USD disbursement to the Solomon Islands to mitigate the economic loss sustained by the pandemic and to pass policies that promote growth in the country.^[International Monetary Fund. June 1, 2020. IMF. https://www.imf.org/en/News/Articles/2020/06/01/pr20229-solomon-islands-imf-executive-board-approves-disbursement-to-address-the-covid-19-pandemic] Following more economic devastation in the Solomon Islands, the ADB approved another 20 million USD to mitigate the effects of the virus and further prevent the disease from entering the country.^[Devdiscourse. June 25, 2020. Devdiscourse. https://www.devdiscourse.com/article/business/1105315-adb-approves-20m-to-help-solomon-islands-combat-covid-19-and-impact-on-economy] 

Overall, the Solomon Islands are struggling with overcrowded living quarters and poor health infrastructure, which has led to difficulty in implementing enforceable and sustainable health measures. Furthermore, while there are currently no reported cases of COVID-19 on the islands, few tests are being conducted. If an outbreak were to occur, the country would struggle to contain it with the current measures in place. 