---
title: "Migrants To and From Ghana: Research Note"
description: Return to [CoronaNet](https://coronanet-project.org/)
author:
  - name: Michaela Balluff
    url: https://www.linkedin.com/in/michaela-balluff-308578164/
    affiliation: 
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>

The unprecedented outbreak and spread of the coronavirus halted the lives of billions of people. However, some groups are more vulnerable to the economic, social, and health impacts of the virus. Since the outbreak, over 50,000 travel restrictions were implemented worldwide^[International Organization for Migration. “Travel Restrictions Related to Travel Routes” June 8th, 2020. Accessed June 10th, 2020. https://migration.iom.int/], leaving migrants and refugees stranded and cut off from their families, with their employment in jeopardy and residence permits expired. At the same time, a high proportion of migrants are working in essential jobs and play a vital role in the COVID-19 response. 

While the African continent was one of the last regions reached by the virus, scholars feared the effect of the disease and its socio-economic repercussions on the population. However, most African states have so far managed to prevent the spread of the virus by introducing strict and extensive policies within a few days of the first reported infections. The Republic of Ghana, with approximately 30 million inhabitants, has one of the highest rates of COVID-19 cases per million on the continent. Despite high rates of infection, Ghana has a comparatively low death rate.^[World Health Organization. “WHO Coronavirus Disease (COVID-19) Dashboard” June 8th, 2020. Accessed June 10th, 2020. https://covid19.who.int/] This rate could be attributed to the advanced health system, extensive testing capabilities, and an established system to trace viruses.^[The Surveillance, Outbreak Response Management and Analysis System (SORMAS) was developed in 2014 in Nigeria to improve the surveillance of the Ebola virus outbreak. Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH. “West Africa: a systematic response to coronavirus” April 17th, 2020. Accessed June 10th, 2020. https://www.giz.de/en/html/84923.html] The first case of coronavirus in Ghana was recorded on March 12th.^[Ministry of Health. “For immediate release: Ghana confirms two cases of COVID-19” March 12th, 2020. Accessed June 10th, 2020. https://ghanahealthservice.org/covid19/downloads/covid_19_first_confirmed_GH.pdf] Three days and four infections later, public gatherings were banned, and schools were closed.^[The Presidency Republic of Ghana. “President Akufo-Addo Addresses Nation On Measures Taken By Gov’t To Combat The Coronavirus Pandemic” March 15th, 2020. Accessed June 10th, 2020. http://presidency.gov.gh/index.php/briefing-room/speeches/1535-president-akufo-addo-addresses-nation-on-measures-taken-by-gov-t-to-combat-the-coronavirus-pandemic] Further restrictions were implemented on March 17th, which barred the entry of travelers who visited a country with more than 200 infections.^[Ministry of Information. “Travel Advisory” March 15th, 2020. Accessed June 10th, 2020. https://drive.google.com/file/d/1NyKu8w7n0eajoBPeiCQn3lIn0FFIf5hN/view] Despite these regulations, cases continued to increase, and the president announced the closure of all borders for human traffic. Additionally, a restriction on the movement of persons in the Greater Accra and Greater Kumasi Metropolitan Area was imposed.^[The Presidency Republic of Ghana. “Address To The Nation By President Akufo-Addo On Updates To Ghana’s Enhanced Response To The Coronavirus Pandemic” March 27th, 2020. Accessed June 10th, 2020. http://presidency.gov.gh/index.php/briefing-room/speeches/1545-address-to-the-nation-by-president-of-the-republic-nana-addo-dankwa-akufo-addo-on-updates-to-ghana-s-enhanced-response-to-the-coronavirus-pandemic-on-friday-27th-march-2020. The Presidency Republic of Ghana. “President Akufo-Addo On Updates To Ghana’s Enhanced Response To COVID-19” April 9th, 2020. Accessed June 10th, 2020. http://presidency.gov.gh/index.php/briefing-room/speeches/1560-president-akufo-addo-speaks-on-updates-to-ghana-s-enhanced-response-to-covid-19]

As of mid-June, Ghana has recorded nearly 12,000 COVID-19 infections and over 50 deaths.^[Ghana Health Service. „COVID-19 Dashboard“ June 15th, 2020. Accessed June 15th, 2020. https://ghanahealthservice.org/covid19/] While the numbers are still increasing, the president announced the easing of restrictions from June 5th onwards. However, all borders will remain closed to human traffic until further notice, while stranded Ghanaian citizens abroad will be assisted with their return to the country.^[The Presidency Republic of Ghana. “Update No. 10: Measures Taken To Combat Spread Of Coronavirus” May 31st, 2020. Accessed June 10th, 2020. http://presidency.gov.gh/index.php/briefing-room/speeches/1597-update-no-10-measures-taken-to-combat-spread-of-coronavirus] 

Similar to other West African countries, Ghana has a longstanding tradition of migration. While the country has achieved lower middle-income country status in the recent decade, hailed as a shining success story in Sub-Saharan Africa, Ghana continues to struggle to provide adequate employment for its labor force.^[International Labour Organization. “ILOSTAT, Labour force by sex and age, modelled estimates” November, 2019. Accessed June 10th, 2020. https://www.ilo.org/shinyapps/bulkexplorer8/] The high population growth in recent years has led to an oversupply of workers, which the labor market is unable to absorb. The population also puts pressure on the available arable land, reinforcing poverty and land scarcity. In 2019, the total unemployment rate was 4.3%, with the youth unemployment rate more than double at 9.2%.^[International Labour Organization. “ILOSTAT, Labour force by sex and age, modelled estimates” November, 2019. Accessed June 10th, 2020. https://www.ilo.org/shinyapps/bulkexplorer8/] Moreover, many Ghanaians work in the informal sector, which is untaxed, unregulated by government institutions, and absent in the gross national product (GNP). These workers have an unreliable source of income and lack access to basic protections and services of the state, making them vulnerable to poverty. To support themselves and their families, many young Ghanaians search for better employment opportunities and economic prospects in urban centers and abroad.^[International Labour Organization. “ILOSTAT, Informal employment and informal sector as a percentage of employment by sex, modelled estimates for 2019” November, 2019. Accessed June 10th, 2020. https://www.ilo.org/shinyapps/bulkexplorer8/]

While the country’s relative political and economic stability attracts immigrants from other countries, Ghanaians continue to search for employment abroad. Large cities in Ghana and other countries offer better wages and employment opportunities. Additionally, transportation services, power supply, health care, access to consumer products, and a life free from family restrictions act as pull factors.^[Anarfi, John Kwasi et al. “Migration From and To Ghana: A Background Paper” Development Research Centre on Migration Globalisation and Poverty. Accra 2010 pp. 15. European Communities. “Push and pull factors of international migration. A comparative report” Luxembourg 2000 p. 75. Ghana Statistical Service. “2010 Population & Housing Census Report: Migration in Ghana” Accra 2014 p. 17.] 

Approximately 15% of Ghanaians are living in a different state than where they were born. The search for better employment opportunities pulls many Ghanaians from rural areas to the urbanized coastal area, resulting in 56.1% of the population living in cities.^[Ghana Statistical Service. “Ghana Living Standards Survey Round 6 (GLSS 6)” August, 2014 pp. 66-72.] Similar to internal migrants, international migrants tend to settle in the major cities of the country. The total number of immigrants to Ghana in 2019 was 466,780, constituting 1.5% of the population. Migrants to Ghana are 31.9 years old on average and mostly arrive from other West African countries, including Togo, Nigeria, and Côte d’Ivoire.^[United Nations Department of Economic and Social Affairs. “Population Division World Population Prospects 2019. International Migration Stock 2019” August, 2019. Accessed June 10th, 2020. https://www.un.org/en/development/desa/population/migration/data/estimates2/estimates19.asp]

Due to the population density and a high travel volume, urban centers are particularly prone to becoming hotspots for the transmission of viruses. Over 80% of COVID-19 infections are in the capital of Accra and the Ashanti Region.^[Ghana Health Service. „COVID-19 Dashboard“ June 15th, 2020. Accessed June 15th, 2020. https://ghanahealthservice.org/covid19/] The large proportion of informal employment further exacerbates the spread of the virus. The workers are already vulnerable and exposed to health hazards. Having daily contact with large numbers of people and living in poor conditions, these workers present a high risk of infection. However, informal workers are dependent on a daily income to afford food and living expenses, making a stay at home order impossible. This dependence on employment for survival influenced the decision of the government to lift restrictions on movement after only three weeks. While the government and NGOs are trying to support people in need, many residents still cannot afford their living expenses and face an uncertain future.^[The Presidency Republic of Ghana. “Address To The Nation By President Akufo-Addo On Updates To Ghana’s Enhanced Response To The Coronavirus Pandemic” April 5th, 2020. Accessed June 10th, 2020. http://presidency.gov.gh/index.php/briefing-room/speeches/1555-address-to-the-nation-by-president-akufo-addo-on-updates-to-ghana-s-enhanced-response-to-the-coronavirus-pandemic. The Presidency Republic of Ghana. “President Akufo-Addo On Updates To Ghana’s Enhanced Response To COVID-19” April 9th, 2020. Accessed June 10th, 2020. http://presidency.gov.gh/index.php/briefing-room/speeches/1560-president-akufo-addo-speaks-on-updates-to-ghana-s-enhanced-response-to-covid-19. The Presidency Republic of Ghana. “President Akufo-Addo Provides Update On Measures Taken Against Spread of COVID-19” April 26th, 2020. Accessed June 10th, 2020. http://presidency.gov.gh/index.php/briefing-room/speeches/1576-president-akufo-addo-addresses-nation-on-update-taken-against-spread-of-coronavirus] Even after the restrictions were lifted, informal workers were subjected to a significant loss of income due to social distancing and work from home directives.

Another vulnerable population during the COVID-19 pandemic are refugees and internally displaced persons. Ghana is currently hosting 12,024 refugees, while 1,306 asylum cases are pending, most of whom originate from neighboring countries in conflict, mainly Côte d’Ivoire, Togo, and Liberia. While some of the refugees settled in Accra and other major cities, most live in one of five refugee camps.^[United Nations High Commissioner for Refugees. “Operational Portal Refugee Situation, Refugees in Ghana” April 30th, 2020. Accessed June 10th, 2020. https://data2.unhcr.org/en/country/gha. Ghana Refugee Board. “Refugee Camp” Accessed June 10th, 2020. https://www.grb.gov.gh/Refugee%20Camp] Refugees in camp settings are extremely vulnerable to the spread of the virus since living conditions are poor, social distancing is often impossible, and health services are difficult to access. 

In 2019, the number of emigrants from Ghana amounted to 970,714, constituting 3.2% of the Ghanaian population. Intra-regional migration was predominant, with 47.3% of all migrants going to other West African countries. 29.1% of migrants traveled to Europe and 20.5% to North America. The top destination countries in 2019 were Nigeria, the United States, and the United Kingdom.^[United Nations Department of Economic and Social Affairs. “Population Division World Population Prospects 2019. International Migration Stock 2019” August, 2019. Accessed June 10th, 2020. https://www.un.org/en/development/desa/population/migration/data/estimates2/estimates19.as] Furthermore, 18,086 persons originating from Ghana were considered refugees in 2018, with an additional 12,557 asylum cases still pending.^[United Nations High Commissioner for Refugees. “Global Trends Forced Displacement in 2018” Geneva 2019 p. 71.]

Migrants from Ghana choose a variety of different ways to leave the country and take regular or irregular routes to reach their destination. The majority of irregular migrants enter the respective country legally but subsequently overstay their visas. However, some migrants try to reach Europe through the Western Mediterranean route from Morocco to Spain or the Central Mediterranean route from North Africa to Italy.^[Frontex. “Migratory Map” January, 2020. Accessed June 10th, 2020. https://frontex.europa.eu/along-eu-borders/migratory-map/. International Organization for Migration. “Irregular Migration from West Africa to the Maghreb. An Overview of Recent Trends” Geneva 2008 p. 9. Schmelz, Andrea. “The Ghanaian Diaspora in Germany. Its Contribution to Development in Ghana“ Deutsche Gesellschaft für Technische Zusammenarbeit (GTZ) GmbH. Frankfurt 2009 p. 7.] According to the International Organization for Migration (IOM), the number of people attempting to cross the Mediterranean Sea through the central route more than doubled in April 2020, while traffic on the Western Mediterranean route sharply declined. Although deaths have decreased, it is to be feared that due to COVID-19 restrictions on ports and the reduced dispatch of search and rescue vessels, shipwrecks will go unnoticed.^[Migration data portal. “Migration data relevant for the COVID-19 pandemic” June 9th, 2020, Accessed June 10th, 2020. https://migrationdataportal.org/de/themes/migration-data-relevant-covid-19-pandemic] Many transit countries have closed their borders, leaving migrants stranded and with no viable option to continue their journey.^[United Nations Africa Renewal. “IOM steps up response for migrants stranded in Niger amidst COVID-19 lockdown” April 2nd, 2020. Accessed June 10th, 2020. https://www.un.org/africarenewal/news/coronavirus/iom-steps-response-migrants-stranded-niger-amidst-covid-19-lockdown] 

Irregular migrants who traveled before borders were closed are still facing an uncertain future. While detected irregular migrants are often returned to their countries through deportation flights, these flights are now halted, leaving the migrants detained in detention centers. Migrants might also be unable to access information about COVID-19 in their language and forgo medical services out of fear of being deported. 

Similarly, domestic workers are unlikely to be able to access adequate information, assistance, and health services. In recent years, the Gulf has become a popular destination for Ghanaian labor migration, especially for women. For many migrants, recruiting occurs through private employment agencies. However, following repeated cases of human rights abuse and mistreatment, the government of Ghana placed a ban on the recruitment of workers to Gulf states in 2017. Nevertheless, a significant number of Ghanaians continue to migrate to the Gulf countries. These migrants do not appear in official statistics, and their total numbers are therefore unknown. Before the ban, between 1,800 and 2,400 Ghanaians migrated annually to the Gulf.^[Atong, Kennedy et al. “Africa Labour Migration to the GCC States: The Case of Ghana, Kenya, Nigeria and Uganda” An African Trade Union Overview. 2018 p. 29; 69.] Following the closure of borders to human traffic, many domestic workers became trapped. Additionally, some employers laid off their workers, leaving them undocumented in the country, as permits are often tied to an employer. The government of Ghana is therefore in the process of evacuating domestic workers, despite the ban on human traffic.^[Azumah, Oswald. “245 Ghanaians in Kuwait to be deported on May 23” May 22nd, 2020. Accessed June 10th, 2020. https://www.myjoyonline.com/news/national/245-ghanaians-in-kuwait-to-be-deported-on-may-23/]

While irregular migrants and domestic workers tend to be less educated, a large number of Ghanaian emigrants are highly skilled. According to an IOM study, 45.7% of Ghanaian migrants have a higher education degree. Thus, Ghana has one of the highest rates of highly skilled migrants in West Africa.^[Docquier, Frédéric; Marfouk, Abdeslam. “Measuring the International Mobility of Skilled Workers (1990-2000) – Release 1.0” 2004 p. 18. European Communities. “Push and pull factors of international migration. A comparative report” Luxembourg 2000 p. 65. International Organization for Migration. “Irregular Migration from West Africa to the Maghreb. An Overview of Recent Trends” Geneva 2008 p. 61.] Similar to all Ghanaians, highly educated workers face unemployment, a lack of career development, and poor working conditions. Therefore, many choose to continue their education or seek employment opportunities abroad. 

The emigration of highly educated Ghanaians is especially striking in the education and health sectors. In 2006, more than half of doctors and a quarter of nurses who trained in Ghana were working abroad.^[International Organization for Migration. “Migration in Ghana. A Country Profile 2009” Geneva 2009 pp. 71; 88. Shaw, William. “Migration in Africa: A Review on Economic Literature on International Migration in 10 Countries” The World Bank. Washington 2007 pp. 25.] While the government has tried to counter the emerging "brain drain" in recent years, Ghanaian migrants are still working at the forefront of the response to the pandemic. Whether working in the health sector or the general labor market, migrants are at a higher risk of being exposed to the virus as most migrants are of working age and are more likely to work in sectors where home-based work is impossible.

The Ghanaian diaspora demonstrates a strong transnational engagement, regularly connecting with family and friends at home through visits, calls, and the purchase of Ghanaian goods. Many Ghanaians abroad are also active in hometown associations (HTA), where members come together to celebrate their culture as well as to promote social development in Ghana.^[Orozco, Manuel. “Diasporas, Development and Transnational integration: Ghanaians in the U.S., U.K. and Germany” Institute for the Study of International Migration and Inter-American Dialogue. 2005 pp. 20-24; 30.]

The personal remittances received in 2019 from Ghanaians in the diaspora were estimated at US$3.5 billion, making Ghana the second-highest remittance-receiving country in Sub-Saharan Africa. In 2018, the highest share of remittances came from the United States, Nigeria, and the United Kingdom.^[The World Bank. “Migration and Remittances, Bilateral Remittance Matrix 2018 (updated October 2019)” October, 2019. Accessed June 10th, 2020. https://www.worldbank.org/en/topic/labormarkets/brief/migration-and-remittances] The remittances accounted for 5.2% of GDP^[The World Bank. “Migration and Remittances, Annual Remittances Data (updated as of April 2020)” April, 2020. Accessed June 10th, 2020. https://www.worldbank.org/en/topic/labormarkets/brief/migration-and-remittances] and were higher than foreign direct investment (FDI) and the official development assistance.^[Organisation for Economic Co-operation and Development. “Development Aid at a Glance” February 14th, 2020. Accessed June 10th, 2020. https://public.tableau.com/views/OECDDACAidataglancebyrecipient_new/Recipients?:embed=y&:display_count=yes&:showTabs=y&:toolbar=no?&:showVizHome=no] However, Sub-Saharan Africa remains the most expensive region to send money to.^[The World Bank. “Remittance Prices Worldwide: An analysis of trends in cost of remittance services” Issue 32. December 2019 p. 1.] Therefore, most remittances go through informal channels, being sent to Ghana through a network of relatives and friends or as shipments of goods, including electronics and IT equipment.^[Anarfi, John Kwasi et al. “Migration From and To Ghana: A Background Paper” Development Research Centre on Migration, Globalisation and Poverty. Accra 2010 pp. 27. Schmelz, Andrea. “The Ghanaian Diaspora in Germany. Its Contribution to Development in Ghana“ Deutsche Gesellschaft für Technische Zusammenarbeit (GTZ) GmbH. Frankfurt 2009 pp. 29.] The money received significantly increases the household welfare in Ghana and can help to minimize economic distress for poor households. While remittances reduce the level and severity of poverty in Ghana, they also increase income inequality.^[Adams, Richard et al. “The Impact of Remittances on Poverty and Inequality in Ghana” Washington 2008 pp. 23. Orozco, Manuel. “Diasporas, Development and Transnational integration: Ghanaians in the U.S., U.K. and Germany” Institute for the Study of International Migration and Inter-American Dialogue. 2005 p. 17. Quartey, Peter. “Ghana” in: Sanket Mohapatra and Dilip Ratha (Eds.) “Remittance Markets in Africa” Washington 2011 pp. 133-154.]

The World Bank estimates that due to the pandemic, the remittance flow to low-and middle-income countries will decrease by approximately 20%. At the same time, the FDI may decline more than 35%, due to travel bans, the disruption of internal trade, and the effects on the global market. Moreover, due to the informal nature of the transfer of money to Ghana, closing borders for human traffic is likely to result in a sharp decline of remittances. In the coming years, remittances will likely remain low.^[The World Bank. “COVID-19 Crisis Through a Migration Lens” Migration and Development Brief 32. April, 2020 pp. 7.]

To date, Ghana has more than 12,000 COVID-19 cases, with infections increasing daily. Even though restrictions are being eased worldwide, it is still unclear when countries will open their borders again. These circumstances make the future for migrants extremely unpredictable. While many migrants lost their employment during the pandemic and remittances are expected to sharply decline, migrants play an essential role in responding to the virus in Ghana and abroad, highlighting the importance of global migration.