---
title: "Lockdown Bangladesh Country Report"
description: Return to [CoronaNet](https://coronanet-project.org/)
author:
  - name: Md. Azmeer Rahman Sorder 
    url: https://www.linkedin.com/in/azmeer-rahman/
    affiliation: University of Dhaka
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
body {
text-align: justify}
</style>


From March 26th, Bangladesh, a South Asian nation, started a nationwide lockdown in response to COVID-19. ^[Kamruzzaman, Md. and Sakib, SM Najmus. March 25th, 2020. Anadolu Agency. https://www.aa.com.tr/en/asia-pacific/bangladesh-imposes-total-lockdown-over-covid-19/1778272]  The first set of lockdown was initially announced for 10 days from March 26th to April 4th, ^[Mamun, Shohel. March 23rd, 2020. The Dhaka Tribune. https://www.dhakatribune.com/bangladesh/2020/03/23/govt-offices-to-remain-closed-till-april-4] but the government gradually extended this lockdown to May 30th. ^[United News of Bangladesh. May 14th, 2020. https://unb.com.bd/category/Bangladesh/general-holidays-extended-till-may-30/51587] The lockdown was officially dubbed as “general holidays”, ^[United News of Bangladesh. March 23rd, 2020. https://unb.com.bd/category/bangladesh/govt-declares-10-day-general-holiday-from-march-26/47790] and applied to all public and private organizations. ^[The Business Standard. March 23rd, 2020. https://tbsnews.net/bangladesh/govt-offices-remain-closed-march-29-april-2-59998] During this time, the government deployed the Bangladesh Police as the primary lockdown and health code enforcing agency, with the Bangladesh Armed Forces deployed side-by-side. ^[Alam, Julhas. March 27th, 2020. The Diplomat. https://thediplomat.com/2020/03/soldiers-enforce-10-day-shutdown-in-bangladesh-to-slow-virus/] By April 5th, the Bangladesh Police had installed checkpoints on major roads around Dhaka to stop ongoing outflow. ^[The Daily Star. April 25th, 2020. https://www.thedailystar.net/except-emergency-services-none-can-enter-or-leave-dhaka-police-1889830] Despite these pen and paper efforts, the flow from Dhaka and inter-district movement continued. ^[Al Amin, Mehedi. April 14th, 2020. The Dhaka Tribune. https://www.dhakatribune.com/bangladesh/2020/04/14/isolation-of-dhaka-narayanganj-districts-dmp-seeks-public-response-narayanganj-seeks-help-from-neighbours]

Until April 10th, enforcing agencies only allowed people to go outside to buy essential groceries and medicine during the restricted shopping time of 10am to 2pm. From April 10th, movement was prohibited before 6am and after 6pm, ^[The New Age Bangladesh. April 10th, 2020. https://www.newagebd.net/article/104143/movement-after-6pm-banned-in-bangladesh] and on May 6th, the prohibition from 6pm was extended to 8pm. ^[The Business Standard. May 6th, 2020. https://tbsnews.net/coronavirus-chronicle/covid-19-bangladesh/govt-relaxes-restriction-going-out-home-78004] In contrast to the rest of the country, the situation in Dhaka was slightly different. Shopping at kitchen markets and super shops was initially allowed until 7pm, but was later set to 5pm. ^[The Business Standard. April 6th, 2020. https://tbsnews.net/coronavirus-chronicle/covid-19-bangladesh/close-shops-supershops-kitchen-markets-6pm-daily-dmp-65857]  ^[The Daily Star. April 11th, 2020. https://www.thedailystar.net/coronavirus-deadly-new-threat/news/kitchen-markets-super-shops-dhaka-must-close-5pm-police-1891900] As the month of Ramadan started, the authorities relaxed the national restrictions on neighborhood shops by extending closing time from 2pm to 4pm, ^[United News of Bangladesh. May 5th, 2020. https://unb.com.bd/category/Bangladesh/shops-shopping-malls-can-operate-10am-4pm-ministry/51135] and allowing restaurants to sell iftar items. ^[The Business Standard. April 27th, 2020. https://tbsnews.net/markets/restaurants-get-permission-sell-iftar-items-74509]  ^[The Dhaka Tribune. April 24th, 2020. https://www.dhakatribune.com/bangladesh/2020/04/24/ramadan-starts-saturday-as-moon-sighted] While the nationwide lockdown was still in place, Bangladesh allowed supermarkets and other shopping centers to open for Eid ul-Fitr markets from May 10th. ^[The Business Standard. May 4th, 2020. https://tbsnews.net/economy/trade/shops-and-shopping-malls-reopen-may-10-77185] Other than a few shopping centers, most failed to follow the proper COVID-19 guidelines. ^[Alif, Abdullah. May 12th, 2020. The Dhaka Tribune. https://www.dhakatribune.com/bangladesh/dhaka/2020/05/12/coronavirus-shops-not-following-health-directives-shut-down-by-dmp] Turnout for these markets was significantly lower than any other year due to the pandemic, which resulted in significant estimated losses for businesses. ^[Bhuiyan, Adnan Hossain. May 17th, 2020. The Financial Express. https://thefinancialexpress.com.bd/trade/clothing-retailers-vendors-counting-loss-in-peak-season-1589686800]

Although cases of community transmission in Bangladesh pointed to mosque congregations, the authorities waited to impose any restrictions on these gatherings until April 6th. ^[Chowdhury, Zia. March 24th, 2020. The Business Standard. https://tbsnews.net/coronavirus-chronicle/coronavirus-bangladesh/coronavirus-residents-fear-community-spread-while] ^[Chowdhury, Zia. April 4th, 2020. The Business Standard. https://tbsnews.net/coronavirus-chronicle/covid-19-bangladesh/many-risk-infection-friday-prayers-mosques-64900] ^[Sakib, SM Najmus. April 6th, 2020. Anadolu Agency. https://www.aa.com.tr/en/asia-pacific/covid-19-bangladesh-halts-prayers-at-mosques/1794191] The number of participants for prayers was capped at five people per prayer and ten people in Friday midday prayer, with an additional ban on iftar gatherings for the month of Ramadan. ^[The Financial Express. April 6th, 2020. https://thefinancialexpress.com.bd/national/bangladesh-restricts-congregation-in-mosques-other-places-of-worship-1586165817] ^[The Financial Express. April 24th, 2020. https://thefinancialexpress.com.bd/national/bangladesh-bans-iftar-gatherings-during-ramadan-1587713005] Once Ramadan started, the number of participants allowed for night prayer increased. ^[The Daily Star. April 24th, 2020. https://www.thedailystar.net/frontpage/news/12-devotees-max-tarabi-prayers-1896253] But this decision was also repealed and mosque congregations were kept free of restrictions from May 6th. ^[United News of Bangladesh. May 6th, 2020. https://unb.com.bd/category/Bangladesh/govt-lifts-restriction-on-offering-prayers-at-mosques/51176] Bangladesh also banned public congregations in open spaces for Eid-ul-Fitr. ^[The Business Standard. May 14th, 2020. https://tbsnews.net/bangladesh/no-eid-prayer-eidgah-open-spaces-year-govt-81481] Defying the ban on mass gathering and religious congregations as well as social distancing instructions, an estimated 100,000 people attended a funeral of a local religious cleric on April 18th in the Brahmanbaria District. ^[Kamruzzaman, Md. April 18th, 2020. Anadolu Agency. https://www.aa.com.tr/en/asia-pacific/bangladesh-massive-funeral-for-cleric-amid-lockdown/1809839] In contrast, Pahela Baishakh, the first day in the Bengali calendar coinciding with April 14th, was not observed with large-scale festivities. ^[Hossain, Md. Ishtiak. April 14th, 2020. United News of Bangladesh. https://unb.com.bd/category/Special/online-celebrations-of-pahela-baishakh-continue-under-shutdown/49550]

Despite government-mandated holidays and a nationwide lockdown, the Bangladesh Garment Manufacturers and Exporters Association (BGMEA) decided to reopen garment factories from April 5th. ^[Rashid, Muktadir. April 4th, 2020. The New Age Bangladesh. https://www.newagebd.net/article/103809/bangladesh-apparel-factory-workers-rush-back-amid-shutdown] BGMEA had a significant impact as an organization due to Bangladesh’s high dependence on garment manufacturing, where Bangladesh is the second largest ready-made garment exporter in the world after China. ^[Mirdha, Refayet Ullah. August 2nd, 2018. The Daily Star. https://www.thedailystar.net/business/export/bangladesh-remains-the-second-biggest-apparel-exporter-1614856] ^[Textile Today. August 5th, 2020. https://www.textiletoday.com.bd/bangladesh-holds-second-position-rmg-exports-wto/] ^[Yardley, Jim. July 24th, 2013. The New York Times. https://www.nytimes.com/2013/07/25/world/asia/garment-trade-wields-power-in-bangladesh.html] BGMEA’s decision to restart factories so early into the lockdown brought fresh panic and harsh criticisms due to a substantial increase in the risk of community transmission. Consequently, BGMEA deferred the opening date of its factories to April 11th, which was later moved to April 26th. ^[Ovi, Ibrahim Hossain, April 4th, 2020. The Dhaka Tribune. https://www.dhakatribune.com/bangladesh/2020/04/04/bgmea-shut-down-factories-till-april-11] ^[Rahaman, Mir Mostafizur, April 16th, 2020. The Financial Express.  https://thefinancialexpress.com.bd/trade/bgmea-to-reopen-its-factories-from-apr-26-1587005862] During this time, garment workers from the remote and poorest regions of the country started their journey back to their workplaces in areas such as Gazipur, Narayanganj and Dhaka without any public transportation due to the nationwide ban on public transportation. ^[Munni, Monira. April 5th, 2020. The Financial Express. https://thefinancialexpress.com.bd/trade/savar-rmg-units-reopen-today-1586055816] ^[The Daily Star. April 4th, 2020. https://www.thedailystar.net/country/news/thousands-returning-dhaka-amid-shutdown-1889497] While factories opened with promises of maintaining health code, hygiene standards and other state-mandated guidelines, these proved to be empty promises as time went by. ^[Uddin, Jasim et al. April 28th, 2020. The Business Standard. https://tbsnews.net/economy/rmg/safety-guidelines-widely-flouted-rmg-factories-74998] ^[Ellis-Petersen, Hannah and Ahmed, Redwan. May 11th, 2020. The Guardian. https://www.theguardian.com/global-development/2020/may/11/bangladesh-garment-factories-reopen-despite-coronavirus-threat-to-workers] ^[BDNews 24. April 27th, 2020. https://bdnews24.com/business/2020/04/27/coronavirus-hotspot-narayanganj-reopens-191-factories-raising-escalation-risks-in-bangladesh]  

Meanwhile, on April 1st, responsibility to present daily COVID-19 briefings was transferred from the Institute of Epidemiology Disease Control And Research (IEDCR), to the Directorate General of Health Services (DGHS). ^[Somoy News English. April 1st, 2020. https://en.somoynews.tv/6777/news/Not-IEDCR-MIS-to-brief-on-coronavirus-situation] On May 3rd, DGHS confirmed that IEDCR would no longer be involved in COVID-19 sample collection, thus making DGHS the prime organization for pandemic management. IEDCR would only be involved with research and quality control of the testing. ^[The Business Standard. May 3rd, 2020. https://tbsnews.net/coronavirus-chronicle/covid-19-bangladesh/dghs-collect-coronavirus-samples-instead-iedcr-76732] The main testing capability of the country was very much limited as sample testing laboratories were scarce in the country. ^[Tajmim, Tawsia. April 2nd, 2020. The Business Standard. https://tbsnews.net/coronavirus-chronicle/covid-19-bangladesh/six-labs-work-testing-so-little-64081] The authorities took the whole month of April to increase the sample testing capacity, which hence increased the number of tests. By the end of April, Bangladesh was able to perform testing of samples in twenty-six state laboratories and three private laboratories instead of six at the beginning of the month. ^[The New Age Bangladesh. April 29th, 2020. https://www.newagebd.net/article/105374/daily-covid-19-detection-tops-600-as-test-increases-in-bangladesh] The number of tests gradually reached four thousand by the end of April, which was still far from any mass testing capacity. ^[Alif, Abdullah. April 27th, 2020. The Dhaka Tribune. https://www.dhakatribune.com/health/coronavirus/2020/04/27/bangladesh-s-capacity-is-far-cry-from-mass-testing] Bangladesh kept increasing the number of testing labs throughout May, and by the end of May conducted about ten thousand tests per day. ^[The Dhaka Tribune. May 10th, 2020. https://www.dhakatribune.com/health/coronavirus/2020/05/10/health-minister-16-more-covid-19-testing-labs-soon] ^[The Dhaka Tribune. July 11th, 2020. https://www.dhakatribune.com/health/coronavirus/2020/07/11/bangladesh-conducts-lowest-covid-19-tests-since-may-30] During this time, the treatment of COVID-19 patients was marred with mismanagement claims and hospitals continued to deny treatment to both infected and non-infected patients alike. ^[The New Age Bangladesh. April 22nd, 2020. https://www.newagebd.net/article/104831/covid-19-treatment-mustnt-be-marred-by-mismanagement] ^[The Daily Star. April 11th, 2020. https://www.thedailystar.net/editorial/news/regular-patients-being-denied-treatment-1891582] ^[The Dhaka Tribune. April 17th, 2020. https://www.dhakatribune.com/health/coronavirus/2020/04/17/coronavirus-mismanagement-at-its-best-at-kuwait-bangladesh-friendship-hospital] The authority had to threaten hospitals to prevent them from refusing the treatment of patients. ^[The Business Standard. May 13th, 2020. https://tbsnews.net/bangladesh/health/no-patient-can-be-sent-back-without-treatment-minister-81049]

Narayanganj District, an industrial hub close to Dhaka, became Bangladesh’s COVID-19 epicenter by the first half of April. ^[Karim, Riadul and Haque, Mojibul. April 12th, 2020. Prothom Alo English. https://en.prothomalo.com/bangladesh/narayanganj-is-now-the-epicenter-of-coronavirus-infection-2] As active and new COVID-19 cases skyrocketed in the district, panic among the Narayanganj residents also rose sharply, ^[Tajmim, Tawsia. April 19th, 2020. The Business Standard. https://tbsnews.net/coronavirus-chronicle/covid-19-bangladesh/sleepless-hotspots-71380] and additional measures to enforce lockdown were taken. ^[The Business Standard. April 10th, 2020. https://tbsnews.net/coronavirus-chronicle/covid-19-bangladesh/surveillance-beefed-enforce-shutdown-narayanganj-67624] However, some Narayanganj residents started to leave the city, defying all measures. ^[BDNews24. April 15th, 2020. https://bdnews24.com/bangladesh/2020/04/15/police-turn-back-500-people-attempting-to-escape-locked-down-narayanganj] As of April 22, at least 21 other districts among the total infected 57 districts had their first COVID-19 positive cases linked with Narayanganj returnees. ^[The Bangla Tribune. April 22nd, 2020. https://www.banglatribune.com/national/news/620099/%E0%A6%95%E0%A6%B0%E0%A7%8B%E0%A6%A8%E0%A6%BE%E0%A6%B0-%E0%A6%B8%E0%A6%82%E0%A6%95%E0%A7%8D%E0%A6%B0%E0%A6%AE%E0%A6%A3-%E0%A7%AB%E0%A7%AD-%E0%A6%9C%E0%A7%87%E0%A6%B2%E0%A6%BE%E0%A7%9F-%E0%A6%A8%E0%A6%BE%E0%A6%B0%E0%A6%BE%E0%A7%9F%E0%A6%A3%E0%A6%97%E0%A6%9E%E0%A7%8D%E0%A6%9C-%E0%A6%A5%E0%A7%87%E0%A6%95%E0%A7%87-%E0%A6%9B%E0%A7%9C%E0%A6%BF%E0%A7%9F%E0%A7%87%E0%A6%9B%E0%A7%87]

From March 23rd, the Supreme Court ordered lower courts to seize functions, with all courts closing from March 29th. This closure was periodically extended to match up with the national lockdown and general holidays, and was later extended beyond the national lockdown. ^[Rahman, Mizanur. March 22nd, 2020. The Dhaka Tribune. https://www.dhakatribune.com/bangladesh/court/2020/03/22/sc-orders-lower-courts-to-postpone-all-activities-except-bail-temporary-injunction] ^[The Dhaka Tribune. March 24th, 2020. https://www.dhakatribune.com/bangladesh/court/2020/03/24/all-courts-to-be-closed-from-march-29-to-april-2] ^[The Financial Express. May 16th, 2020. https://thefinancialexpress.com.bd/national/court-holidays-extended-until-may-30-1589636476] ^[The Daily Star. August 3rd, 2020. https://www.thedailystar.net/country/news/lower-courts-start-regular-operation-aug-5-1939605] While this closure occurred, the court authority decided to start the court functions in a limited scale, but quickly went back on the proposal. ^[The Daily Star. April 23rd, 2020. https://www.thedailystar.net/country/news/cj-small-scale-court-activities-amid-extended-closure-1896181] ^[The Daily Star. April 25th, 2020. https://www.thedailystar.net/coronavirus-deadly-new-threat/news/chief-justice-suspends-decision-run-court-functions-short-extent-1896664] From May 11th, the Supreme Court decided to introduce a virtual court. ^[The Business Standard. May 11th, 2020. https://tbsnews.net/bangladesh/court/supreme-court-virtual-courts-start-taking-applications-80086]

As the day of Eid ul-Fitr approached, the authorities tasked to maintain lockdown and social distancing measures started relaxing its enforcement. ^[Kamruzzamun, Md. May 23rd, 2020. Anadolu Agency. https://www.aa.com.tr/en/asia-pacific/eid-preparation-horde-may-worsen-pandemic-in-bangladesh/1851461] ^[Alam, M Jahangir. May 6th, 2020. United News of Bangladesh. https://unb.com.bd/category/Special/relaxed-lockdown-taken-as-license-to-ignore-social-distancing/51197] Subsequently, check posts around Dhaka were removed and the authorities allowed people to leave and enter Dhaka without any restrictions. ^[Adhikary, Tuhin Shubhra and Hasan, Rashidul. May 23rd, 2020. The Daily Star. https://www.thedailystar.net/frontpage/news/thousands-leave-city-amid-relaxed-travel-curbs-1905244] Complying with the earlier announcement of not extending the nationwide lockdown from May 30th, Bangladesh ended its lockdown on May 30th. ^[The Business Standard. May 27th, 2020. https://tbsnews.net/coronavirus-chronicle/covid-19-bangladesh/general-holiday-not-extend-further-state-minister-85870]

From March 26th to May 30th, the nationwide lockdown period, almost all of Bangladesh’s policies had either non-existent, weak or moderate enforcement. Government introduced policies in accordance with the religious sentiment of the public, hence repeating the same lack of priority placed on the pandemic as the pre-lockdown period.
